option-t/option-t

- src/OptionT.js
> Fix the returned type of Option<T>.mapOr().

- CHANGELOG.md
- src/OptionT.js
We accept current signitures of these APIs as stable.
When Rust's upstream changes these APIs, we might follow them with bumping our major version.
> Make `Option<T>.mapOr()` and `Option<T>.mapOrElse()` stable.

- CHANGELOG.md
- README.md
- src/index.js
- test/test_inheritance.js
This library considers 2 type systems, ECMA262 5th' one and TypeScript's one.
So there are some way to detect whether this object is a `OptionT.Option<T>`:
In ECMA262 5th, there is no interface system. Thus we can detect the
object type by checking `__proto__` like this.
```
var isOptionT = some instanceof OptionT.OptionT.
```
In TypeScript, there is interface system and static type checking!
So we can use interface to do it and it is checked statically.
```
function isSome<T>(option: Option<T>): boolean {.......}
```
By the way, this might be a problem to confuse "what API should use in
our script? `OptionT.OptionT`? or `OptionT.Option<T>?`".
So this change makes the name of 'base class' more explicitly
and marks the legacy name as deprecated.
* Add `OptionT.OptionBase`.
* Mark …
> Add OptionT.OptionBase & Mark OptionT.OptionT as a deprecated API.

- CHANGELOG.md
- src/OptionT.js
- src/index.js
This was [marked as deprecated](https://github.com/saneyuki/option-t.js/pull/66) in 0.10.x
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/67)
> Remove OptionT.OptionT

- option-t.d.ts
- test/test_type_definition.ts
This proves that we don't need to define Promise like interface by self and we can use Promise type definitions from outside.
see also: #72
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/73)
> Use 'typescript/bin/lib.es6.d.ts' for our tests.

- package.json
At now, we must follow SPDX license expression syntax version 2.0 string.
https://docs.npmjs.com/files/package.json#license
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/74)
> Fix the npm's warning about license field.

- CHANGELOG.md
- test/test_type_definition.ts
- tsconfig.json
TypeScript 1.5 and later supports ES6 target, and TypeScript's external modules will transition to ES6 module semantics.  So this change make option-t supports only ES6 target officially.
- If you don't use TypeScript, you don't have to worry about using this
package. You can continue to use this as a common.js package.
- If you use TypeScript with targeting ~ES5, you might need to change your code. Sorry. We're supporting only targeting ES6 after this change. 
- However, you will be able to use this type definition with to import some ES6 Promise compatible type definitions (Sorry, we have not established it yet.)
- If you use TypeScript with using inner modules (as known as 'namespace'),
we have not supported it yet. If you'd like to need to import this package as an inner module, …
> TypeScript's type definition only supports ES6 target

- package.json
- src/OptionT.js
- test/test_initialize.js
Hi, saneyuki.
I found that
```javascript
new None() instanceof Some
```
returns `true` . And, 
```javascript
new Some('hoge') instanceof None
```
also returns `true` .
It is caused by using same prototype for Some and None at [here](https://github.com/saneyuki/option-t.js/blob/06be0fe1f90b3a4ac374c4d8f0950a59062d0864/src/OptionT.js#L305) and [here](https://github.com/saneyuki/option-t.js/blob/06be0fe1f90b3a4ac374c4d8f0950a59062d0864/src/OptionT.js#L328).
I make there to use different prototype in those classes, and write test case.
Thank you.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/78)
> Use different prototype in Some and None, not same one

- CHANGELOG.md
- option-t.d.ts
- test/test_type_definition.ts
Generally, in some static typing environments as TypeScript, Flowtype, and etc, we should use an interface strongly, not to use class base typing  like `instanceof`.
However, if we cooperate with some library that provides the runtime assertion which uses `a instanceof A` like React's `React.PropTypes` for cooperating with some other vanilla JavaScript ones, we requires the checking systems which is based on `instanceof`.
So this commits exposes `OptionBase` to our type definition to cooperate with them. This is needed for real world usecases.
The typical case is [TSX (TypeScript JSX) syntax](https://github.com/Microsoft/TypeScript/wiki/JSX).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/77)
> Expose OptionBase in the type definition.

- CHANGELOG.md
- option-t.es6.d.ts
- package.json
- test/test_type_definition_es6.ts
- tsconfig.json
At [TypeScript 1.6](http://blogs.msdn.com/b/typescript/archive/2015/09/16/announcing-typescript-1-6.aspx), the module resolution behavior is changed. It only accepts ES6 module syntax if we use `--moduleResolution node` mode.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/83)
> Add option-t.es6.d.ts to support '--moduleResolution node'.

- .travis.yml
- Use an only latest version of each Node.js major one.
- Stop to test on a legacy version.
- Remove Node v0.12 and io.js
- We don't have to test on all versions to confirm this library works well in ES5 environment.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/84)
> Clean up TravisCI config

- CHANGELOG.md
- option-t.d.ts
- option-t.es6.d.ts
- tsconfig.json
In this case, we'd like to treat `v` as `None<T>` in the arm `B`.
```typescript
const v: Option<T> = ...;
if (v.isSome) {
// In this arm A, `v` is `Some<T>` by the type guard method
}
else {
// In this arm B, `v` should be `None<T>`  by the type guard method,
// but the current `Option<T>` is just a interface, which cannot restrict type "range".
}
```
So this change make this library more Rust's enum style!
- Define `type Option<T> = Some<T> | None<T>`.
- just as a union type.
- Rename `interface Option<T>` to `interface OptionMethods<T>`
- User cannot implement `OptionMethods<T>` to their types.
- But I don't think this would be a serious problem.
- Who want to implement a self-defined `Option<T>`?
- They would extend `Some` or `None`.
- If someone want to implements custom type, we'll …
> refactor(type): Option<T> should be either Some<T> or None

- src/OptionT.js
- test/option-t/test_flatmap.js
- test/option-t/test_or_else.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/116)
> refactor(OptionT): throw TypeError if andThen/orElse's callback returns non-Option type

- CHANGELOG.md
- src/Option.js
- src/Result.js
- test/manifest.js
- test/option-t/test_expect.js
- test/option-t/test_unwrap.js
- test/result-te/test_unwrap.js
- test/result-te/test_unwrap_err.js
These should be TypeError to explain their semantics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/132)
> refactor(TypeError) throw 'TypeError' instead of 'Error'

- CHANGELOG.md
- src/Option.d.ts
- src/Result.d.ts
Fix https://github.com/saneyuki/option-t.js/issues/155
This reverts commit 8b18e62100df6b52e13ff37a2869c7edf26cffff.
I'll backout it by these reasons:
1. I thought this change is not useful for almost use cases.
We use `Option<T>` as an opaque type. Of course `Option.isSome` with type guard is
useful to know a actual type,
but this is useful only if we calls `Option.unwrap()` or `Option.expect(msg);`.
In other case, this narrowing does not have a concrete benefit.
2. Using literal type has some benefit to avoid calling instance method function.
So it might have some benefit to keep `isSome` or `isNone`
as a property instead of a type guard function
(`isSome(): this is Some<T>`) for performance aspects.
As a basic data structure, less overhead is very important metrics.
However, …
> Revert "refactor(api): use literal type"

- src/Option.d.ts
- src/Result.d.ts
- test/option-t/test_type_definition.ts
- test/result-te/test_type_definition_es6.ts
This fixes these things:
- Define constructors and interfaces of instance with same approach with
to define a builtin object.
- `new Some<T>(v)` and `new None<T>()` will be an object which is typed
as `Option<T>`
- `new Ok<T, E>(v)` and `new Err<T, E>(e)` will be an object which is
typed as `Result<T, E>`
- `Some` or `None`'s members are specialzed.
- This retries https://github.com/saneyuki/option-t.js/pull/152
- This avoid the regression: https://github.com/saneyuki/option-t.js/issues/155
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/157)
> refactor(typing): Reorganize d.ts for specializing member properties

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/161)
> Add Node v6 to our build matrix

- bors.toml
This feature was literally added to bors-ng with Reviewable in mind.
https://github.com/bors-ng/bors-ng/pull/210
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/183)
> Remove Reviewable boilerplate from merge commits

- CHANGELOG.md
- gulpfile.js
This fixes that some files in `option-t/esm` are not ES module.
- `option-t/esm`
- `option-t/esm/Option`
- `option-t/esm/Result`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/201)
> Fix the bug which does not emit some modules as es module syntax into esm/.

- CHANGELOG.md
- src/Maybe/and.ts
- src/Maybe/index.ts
- src/Maybe/or.ts
- src/Nullable/and.ts
- src/Nullable/index.ts
- src/Nullable/or.ts
- src/PlainOption/index.ts
- src/PlainOption/or.ts
- src/PlainResult/index.ts
- src/PlainResult/or.ts
- src/Undefinable/and.ts
- src/Undefinable/index.ts
- src/Undefinable/or.ts
This is breaking change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/208)
> Rename `andBar()`/`orBoo()` -> `andForBar()`/`orForBar()`.

- CHANGELOG.md
- src/PlainResult/index.ts
You can use `import { ok, err, } from 'option-t/esm/PlainResult';` instead of `import { toOptionFromOk, toOptionFromErr, } from 'option-t/esm/PlainResult';`.
- https://github.com/karen-irc/option-t/issues/217
- https://github.com/karen-irc/option-t/issues/216
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/219)
> Add the alias for toOptionFromOk/toOptionFromErr

- CHANGELOG.md
- gulpfile.js
- tsconfig.json
- Our shipping code is down-level transformed. But ours not a complicated transform. We can read the transformed code.
- For debugging purpose, Showing _transformed_ code would be better if it's not complicated.
- Thus We stop to ship a source map.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/220)
> Unship a source map

- CHANGELOG.md
- src/Result.js
- src/index.d.ts
- src/index.js
- test/Maybe/test_type_guard.js
- test/Nullable/test_type_guard.js
- test/PlainOption/test_create.js
- test/PlainOption/test_type_guard.js
- test/PlainResult/test_create.js
- test/PlainResult/test_type_guard.js
- test/Undefinable/test_type_guard.js
- test/manifest.js
- test/option-t/test_and.js
- test/option-t/test_drop.js
- test/option-t/test_expect.js
- test/option-t/test_flatmap.js
- test/option-t/test_inheritance.js
- test/option-t/test_initialize.js
- test/option-t/test_json.js
- test/option-t/test_map.js
- test/option-t/test_map_or.js
- test/option-t/test_map_or_else.js
- test/option-t/test_or.js
- test/option-t/test_or_else.js
- test/option-t/test_type_definition.ts
- test/option-t/test_unwrap.js
- test/option-t/test_unwrap_or.js
- test/option-t/test_unwrap_or_else.js
- test/result-te/test_type_definition_es6.ts
- test/utils.js
- After we merged [#221](https://github.com/karen-irc/option-t/pull/221), we can remove them.
- If you expect that a minifier preserve `@license` comment to preserve license comment, you should care this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/222)
> Remove License header comment

- src/Maybe/do.ts
- src/Maybe/index.ts
- src/Maybe/tap.ts
- src/Nullable/do.ts
- src/Nullable/index.ts
- src/Nullable/tap.ts
- src/PlainOption/do.ts
- src/PlainOption/index.ts
- src/PlainOption/tap.ts
- src/PlainResult/do.ts
- src/PlainResult/index.ts
- src/PlainResult/tap.ts
- src/Result.d.ts
- src/Undefinable/do.ts
- src/Undefinable/index.ts
- src/Undefinable/tap.ts
- src/utils/Function.ts
We rename `do()` functions to `tap()` at all to sort with [`rxjs`](https://github.com/ReactiveX/rxjs)
or [`ixjs`](https://github.com/ReactiveX/IxJS).
We leave `do()` as an alias for `tap()` with a backward compatibility.
You code will works well if you don't change your code on updating this version.
_But it will be gone in the next major release_. We recommends to change your code.
Basic migration guides is here:
- Instead of `DoFn`, import `TapFn` from `option-t/***utils/Function`.
- If you use `import { doOnA } from 'option-t/***/A/do';`, instead use `import { tapA } from 'option-t/***/A/tap';`.
- If you use `import AMod from 'option-t/***/A'; AMod.do();`, instead use `import AMod from 'option-t/***/A'; AMod.tap();`.
---
This change is [<img …
> Add tap() to sort with rxjs/ixjs

- CHANGELOG.md
See https://github.com/karen-irc/option-t/issues/232
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/233)
> Deprecate `instanceof` checking for option-t/lib/Option and option-t/lib/Result

- src/Maybe/map.ts
- src/Nullable/map.ts
- src/Undefinable/map.ts
If `U` is `Maybe<SomeType>`, we think naturally the returned value of this function would be
the nested type `Maybe<Maybe<SomeType>>`. But this type means `(SomeType | null | undefined) | null | undefined`.
So a type checker would recognize this type as `SomeType | null | undefined`. So it's flattened.
Then the user should call `andThen` (_flatmap_) operation instead of this.
And we should throw the error for it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/236)
> Add the comment why we check the returned value type from selector in map operation

- CHANGELOG.md
- src/Option.d.ts
- src/Option.js
- src/Result.d.ts
- src/Result.js
see https://github.com/karen-irc/option-t/issues/232
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/277)
> Add the jsdoc to constructors which are planned to deprecate

- src/Option.d.ts
- src/Option.js
- src/Result.d.ts
- src/Result.js
- test/option-t/test_inheritance.js
- test/result-te/test_inheritance.js
- Obsolete `instanceof` checking for `lib/Option` and `lib/Result`.
- Overhaul type definitions for `lib/Option` and `lib/Result`.
- If your code use their type definitions, this may breaks your code.
- Rename `ResultBase._is_ok` to `ResultBase._isOk`.
- These are private APIs. You should not use this.
- Fix https://github.com/karen-irc/option-t/issues/232
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/287)
> Obsolete instanceof checking for Option/Result 

- Makefile
* If we add `__` prefix to each of targets, they will not shown in
tab-completion in bash with autocomplete script.
* We can mark a public targets with a magic comment which helps by
`make help`.
* We should use `__` to a target which have some states and you cannot
call it from outer script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/301)
> Remove __ prefix from make's targets

- tsconfig_cjs.json
- tsconfig_esm.json
* We ensure the build result with `make test` which depends on `make build`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/315)
> Remove unnecessary 'src' field from tesconfig_*.json

- yarn.lock
[yarnpkg v1.10~](https://github.com/yarnpkg/yarn/releases/tag/v1.10.0) adds `integrity` fields to `yarn.lock`. This breaks [checking git-diff in our CI](https://github.com/karen-irc/option-t/blob/b83e8c26bf1c08c3152fcf1c4c01b3f66be01d18/Makefile#L209).
So this pull request fixes it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/317)
> Update yarn.lock with yarnpkg v1.10~

- .travis.yml
This avoid the failure by changing yarn.lock format by yarnpkg change.
By this change, we need to specify the version of yarnpkg.
It increases our maintenance burden.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/318)
> Specify yarnpkg version explicitly

- src/shared/Function.ts
By [TypeScript 3.2](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html)'s `strictBindCallApply` option, the below code would be a compile error.
```typescript
const fn: (this: number, input: number) => string => function (a) {
return String(a);
}.bind(1);
const input: Nullable<number> = 1;
// compile error: `fn` type is mispatched with `(this: void, v: T) =>U`.
const r: Nullable<number> = mapForNullable(input, fn);
```
I think this might be one of rare cases.
But I also think we should relax the type of `this` for callback functions.
By this change, we remove `this: void` from all callback functions' type. This allow the above sample code.
You can seem this change will introduces a new pitfall like this:
```typescript
mapForNullable(input, function (v) {
return …
```
> Relax `this` type for callback functions

- ava_test/PlainResult/test_map_or_else.js
- ava_test/Result/test_map_or_else.js
- src/PlainResult/index.ts
- src/PlainResult/mapOrElse.ts
- src/Result.d.ts
- src/Result.js
This API is still experimental in rust.
https://doc.rust-lang.org/std/result/enum.Result.html#method.map_or_else
But I think this is useful and it's easy to make this compatible
for the future breaking change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/327)
> Implement mapOrElseForResult<T, E, U>

- CHANGELOG.md
- README.md
* Basically, we recommend to use _utility types & functions_.
* _Wrapper objects_ has some downside if your project has multiple versions of this package in its project dependencies.
* `instanceof` might work unexpectedly if you `(a instanceof b)` in this case.
This is confusable behavior.
* `a` is created by the constructor provided by the version _a_ of this.
* `b` is the constructor provided by the version _b_ of this.
* Bloat bundle size unnecessarily.
* It's hard for almost JS code minifier to minify a property on prototype chain.
* So we decide to no-recommend _wrapper objects_ without any strong motivation.
* This does not means to make them obsolete or deprecate **now**.
* We don't have any concrete plan to deprecate these API.
* Of course, however, we would lower priorities of …
> Add the guide to no recommendation to use wrapper objects in almost case

- .travis.yml
This does not mean that this code will not run with Node.js v8 immediately.
But this allow to introduce a change which is incompatible with Node v8
Fix https://github.com/karen-irc/option-t/issues/324
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/338)
> Drop Node.js v8 from out CI

- Makefile
This fix the regression by https://github.com/karen-irc/option-t/pull/339, which is that `make build -j && make build -j` would not work correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/343)
> Clean up TMP_MJS_DIR correctly

- src/Maybe/Maybe.ts
- src/Nullable/Nullable.ts
- src/Undefinable/Undefinable.ts
TypeScript compiler has builtin
`NonNullable<T> = T extends null | undefined ? never : T`.
So I named `Not***` for introduced types.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/344)
> Add _non nullable_ types by conditional types

- tools/eslint/eslintrc_core.js
We should move our eslint rule base to the fork version,
[eslint-config-abema](https://github.com/cats-oss/eslint-config-abema),
instead of [eslint-config-fluct](https://github.com/voyagegroup/eslint-config-fluct)
because I intend to use typescript-eslint rule in eslint-config-abema.
We need to sort the base.
https://github.com/karen-irc/option-t/issues/350
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/351)
> Migrate the base rule sets of eslint to eslint-config-abema

- package.json
- src/index.ts
* Stop expose `src/Option` via `src/index`.
* This sort the usages with other APIs which this pacakge provides.
* For the future, we might provide all APIs from this entry points
* https://github.com/karen-irc/option-t/issues/232
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/365)
> Make `import {} from 'option-t'` meaningless

- test/option-t/test_flatmap.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/373)
> Fix misusing assert.notStrictEqual() in the test for Option<T>.flatMap()

- src/Option.d.ts
- src/Result.d.ts
We have already written this reason in README.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/379)
> Add comments why we don't recommend to use wrapper objects

- ava_test/PlainOption/test_object_shape.js
- ava_test/PlainResult/test_object_shape.js
- src/PlainOption/Option.ts
- src/PlainResult/Result.ts
We add these properties on creating by factory functions to stabilize their object Shape (SpiderMonkey)/Structure (JavaScriptCore)/Hidden Class (V8).
* `PlainOption::None.val`
* `PlainResult::Ok.err`
* `PlainResult::Err.val`
This change adds the test case to ensure to do it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/395)
> Add the test to ensure properties on objects 

- Makefile
- package.json
- tools/babel/babelrc.power_assert.js
- yarn.lock
power-assert is super useful tool, but:
1. It's sometimes mantainance burden on upgrade babel.
2. We're moving to ava.
So I'll remove it to make our build pipeline simple.
If we abandan to move to ava, then we may recover power-assert.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/446)
> Remove power-assert

- README.md
- src/Option.d.ts
- src/Option.js
- src/Result.d.ts
- src/Result.js
Fix https://github.com/karen-irc/option-t/issues/459
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/460)
> Mark legacy `Option<T>` and `Result<T, E>` as deprecated

- .circleci/config.yml
Node.js v12 has been in LTS.
We can drop v10.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/484)
> Drop Node.js v10 and replace it by v12 from our CI

- .eslintrc.js
- Makefile
- tools/babel/babel-plugin-add-mjs-suffix.js
- tools/babel/babelrc.mjs.pathrewiter.js
- tools/esmodule_path_rewrite_tester.js
Node.js bultin ESM support requires `.mjs` extention for import/export path
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/520)
> Fix all import/export path in esm/

- tools/babel/babel-plugin-add-mjs-suffix.js
This fix to throw TypeError for the case `export { a, b };`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/523)
> Early return correctly if import/export declaration does not have StrngLiteral as _source_

- README.md
Now, Node.js supports an ES Module natively. It's the time to deprecate this dir.
Why did we introduce `option-t/lib`?
---------------------------------------
We introduce this dir to support a following usecase when Node.js did not support ES Module natively.
```javascript
// a,js
import { isNull } from 'option-t/esm/Nullable/Nullable';
console.log(isNull(1));
```
When you would like to this code universally (both Node.js and browsers via webpack or other bundlers), you would face some problem.
If you convert and bundle this code by webpack or others, this code would be run and bundlers do tree shaking nicely.
However, if you transform this code to commonjs or other classic module type
which is able to run on Node.js by using babel or other transformers, it code will not run on your …
> Deprecate `option-t/lib`

- src/Maybe/tap.ts
- src/Nullable/tap.ts
- src/Undefinable/tap.ts
We added these functions to
* Sort with other types.
* Future enhancement for pipelining functions.
Generally, simple `if` statement would be readable and efficient.
> Not recommend tap() for Nullable/Undefinable/Maybe generally

- Makefile
- tools/package_json_rewriter/json.js
- tools/package_json_rewriter/main.js
- tools/package_json_rewriter/tester.js
We require this to publish this project as Dual CommonJS/ES Module Packages.
We would not like to maintain `exports` field in package.json by hand.
https://github.com/karen-irc/option-t/issues/421
> Generate package.json to allow to transform it

- tools/package_export_tester.js
- tools/package_json_rewriter/main.js
- tools/package_json_rewriter/transformer/add_exports_field/compatibility.js
- tools/package_json_rewriter/transformer/add_exports_field/main.js
By the behavior of Node.js v13.8, if we add `exports` field once even if its object is empty `{}`, user could not load all subpaths by `option-t/esm/Bar/Foo`. This causes a breaking change.
As preparing https://github.com/karen-irc/option-t/pull/575, I'd like to add all exist paths to `exports` field in package.json once. This keep backward compatibility.
By contrast with conditional exports, `exports` field does not emit any warning. I seem we can regard it as stable.
* https://github.com/karen-irc/option-t/pull/575
* https://github.com/karen-irc/option-t/issues/421
> Add exist paths to 'exports' fields in package.json

- package.json
- tools/package_json_rewriter/transformer/add_exports_field/main.js
This error happens by this change in [Node.js v13.10](https://github.com/nodejs/node/pull/31625) and I think we can regard this problem as the regression of this library.
For the future, we should wait https://github.com/nodejs/node/issues/32107 but it is still in progress.
This patch will try to workaround for it.
* https://github.com/nodejs/node/pull/31625
* https://github.com/nodejs/node/issues/32107
* https://github.com/babel/babel/issues/11216
> Fix `ERR_PACKAGE_PATH_NOT_EXPORTED` error on loading `option-t`.

- Makefile
- package.json
- tools/extension_renamer.js
- yarn.lock
We don't use this cli much. So we can replace our hand-written script.
By this change, we can suppress security concern alert caused by `rename-cli#yargs#os-locale#mem`.
> Remove renamer-cli from depdendencies

-  .github/workflows/ci_packaging.yml
- .editorconfig
For matrix build, GitHub Actions is better than CircleCI.
> Run to test for 'exports' field in package.json on GitHub Actions

- .github/workflows/ci_packaging.yml
actions/setup-node has not supported 12.7 or later yet.
> Run GitHub Actions CI test in container

- tools/esmodule_path_rewrite_tester.js
- tools/package_export_tester.js
Node v12.17 unflagged ESM support
https://nodejs.org/en/blog/release/v12.17.0/
> Enable tests using dynamic import for Node v12

- __tests__/.eslintrc.js
Mysteriously, the previous settins causes many warnings happens only in CI...
Is this reproducible on Linux? (But I don't have any environments).
I suspect this is caused by using typescript-eslint for JS files.
So I fix it in this change.
> Suppress warnings in __tests__

- .github/dependabot.yml
I misread [the doc](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates) and disabled them
> Enable dependency update by dependabot

- .github/dependabot.yml
- package.json
- yarn.lock
This is required to migrate __tests__/ to TypeScript by ts-migrate https://github.com/karen-irc/option-t/pull/715
> Upgrade TypeScript compiler to v4.0

- src/PlainResult/unwrap.ts
- src/PlainResult/unwrapOr.ts
- `unknown` is _top type_. We can assign any of types to it.
- From TS 3.5, [Generic type parameters are implicitly constrained to `unknown`](https://devblogs.microsoft.com/typescript/announcing-typescript-3-5/). Thus the behavior is not changed after this patch. This changes to more explicit way.
- Ideally, we wanted to use `never` type. But `never` type is _bottom type_. So we cannot assign `Ok<T>` to `Ok<never>`.
- Overloading has some problem with intellisense. It's not nice for productivity and this kind of troubles are happened in old days of rxjs.
Fix #791
> Omit unused generic type parameters from unwrap/unwrapErr/unwrapOr for PlainResult

- package.json
- tools/package_json_rewriter/transformer/add_exports_field/main.mjs
- tools/package_json_rewriter/transformer/add_exports_field/public_api.mjs
- tools/public_api.mjs
We use 'exports' field so we don't have to keep this.
Fix https://github.com/karen-irc/option-t/issues/803
> Remove 'main' field from package.json

- tools/package_export_tester.mjs
- tools/package_json_rewriter/transformer/add_exports_field/compatibility.mjs
- If we disable this flag, we would not export lib/.
- But the published package would contains files under lib/.
- It should be separated issue to make the release easy
- https://github.com/karen-irc/option-t/issues/808
> Add the flag to switch to expose lib/

- CHANGELOG.md
- CHANGELOG_OLD.md
- Makefile
- package.json
- tools/pkg_files.json
It's tired effort to maintain changelogs and GitHub release page on releasing each versions.
We moved to publish to npm semi-automatically on creating github release.
- https://github.com/karen-irc/option-t/pull/853
- https://github.com/karen-irc/option-t/pull/852
- https://github.com/karen-irc/option-t/pull/851
So this intend to stop to update a changelog as a file.
> Move Changelog to GitHub's release page

- .github/workflows/publish_package_to_npm.yml
This task will be executed by `make publish`
This followup https://github.com/karen-irc/option-t/pull/853
> Remove needless steps from publish to npm action.

- .eslintrc.cjs
- __tests__/ClassResult/and.test.mjs
- __tests__/ClassResult/and_then.test.mjs
- __tests__/ClassResult/drop.test.mjs
- __tests__/ClassResult/drop_with_destructor.test.mjs
- __tests__/ClassResult/err.test.mjs
- __tests__/ClassResult/expect.test.mjs
- __tests__/ClassResult/inheritance.test.mjs
- __tests__/ClassResult/initialize.test.mjs
- __tests__/ClassResult/map.test.mjs
- __tests__/ClassResult/map_err.test.mjs
- __tests__/ClassResult/ok.test.mjs
- __tests__/ClassResult/or.test.mjs
- __tests__/ClassResult/or_else.test.mjs
- __tests__/ClassResult/unwrap.test.mjs
- __tests__/ClassResult/unwrap_err.test.mjs
- __tests__/ClassResult/unwrap_or.test.mjs
- __tests__/ClassResult/unwrap_or_else.test.mjs
- src/Option.d.ts
- src/Option.js
- src/Result.d.ts
- tools/platform.mjs
- tools/spawn.mjs
These comments are covered by /LICENSE.MIT
> Remove duplicated MIT License header comment

- src/Option.js
- src/Result.js
- tools/babel/babelconfig.mjs
- For long term maintainability, we'd like to migrate these code to ES6 code base.
- By this change, we use babel's loose transform to reduce the result code size.
- By this change, their member functions are renamed. If user code base has a bad code which depends on stack trace, this will break them.
> Use ES6 partially for classic wrapper objects

- README.md
- __tests__/ClassOption/inheritance.test.mjs
- __tests__/ClassOption/initialize.test.mjs
- __tests__/ClassOption/type_definition.ts
- __tests__/ClassResult/inheritance.test.mjs
- __tests__/ClassResult/initialize.test.mjs
- __tests__/ClassResult/type_definition_es6.ts
- src/ClassOption/ClassicOption.d.ts
- src/ClassOption/ClassicOption.js
- src/ClassResult/ClassicResult.d.ts
- src/ClassResult/ClassicResult.js
- src/Option.ts
- src/Result.ts
I got a feedback that:
- some projects are still continue to use old version with pinning the old version.
- method chaining style is nice to use.
By these feedback, I revive some removed APIs to allow to migration to the newer version.
After some internal re-layout and some evolving typescript compiler, we can add these legacy APIs without invading intellisense.
- We continue to recommend to not use classic wrapper objects.
- But their method chain should not be marked as deprecated for people that like method chain style.
After this change, these code pattern will continue to be `false`.
- `option instanceof Some`
- `option instanceof None`
- `option instanceof Ok`
- `option instanceof Err`
- https://github.com/karen-irc/option-t/pull/364
> Revive constructors of classic wrapper objects for compatibility

- src/PlainResult/index.ts
We would like to remove these.
In Rust, `Option<T>` is a 1st citizen. So I think it's beneficial to
provide conversions as a short name.
But this is not.
Generally, `null` may be more better choice in JavaScript.
So the time is over to treat these function as special case.
> Mark `ok`/`err` export from PlainResult/index as deprecated.

- __tests__/PlainOption/drop.test.mjs
- __tests__/PlainResult/drop/test_drop_both.test.mjs
- __tests__/PlainResult/drop/test_drop_err.test.mjs
- __tests__/PlainResult/drop/test_drop_ok.test.mjs
- src/PlainOption/drop.ts
- src/PlainResult/drop.ts
This operator is expected to use as a destructor.
So we should do these in them:
-  release the field aggressively
- freeze the object to prevent reuse it.
> unsafeDrop() should release the field and freeze itself.

- .github/dependabot.yml
see https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#specifying-dependencies-and-versions-to-ignore
> Allow dependabot to update typescript's patch version

- Makefile
- package.json
- tools/cp_files.mjs
- tools/parse_argv.mjs
- yarn.lock
We'd like we'd like to clear GitHub's noisey vulnerable alert which says that cpx's dependency contains some vulnerable packages.
(This alert does not affect this package actually)
But It looks that [cpx](https://github.com/mysticatea/cpx) has not been updated since 2018.
So we replace it with simple node.js script
> Replace cpx with the simple node.js script

- README.md
We removed the support to import with file extensions in [v28.0.0](https://github.com/karen-irc/option-t/releases/tag/v28.0.0).
> Remove the metion about file extension from README

- .github/workflows/ci.yml
v14 enters maintenance LTS. We don't have to support them as Tier 1.
https://nodejs.org/en/about/releases/
> Drop Node.js v14 from CI

- tools/cp_files.mjs
- tools/extension_renamer.mjs
- tools/generate_import_path_list_markdown.mjs
- tools/glob.mjs
- tools/package_json_rewriter/json.mjs
- tools/package_json_rewriter/main.mjs
- tools/package_json_rewriter/transformer/add_exports_field/ExportEntry.mjs
- tools/package_json_rewriter/transformer/add_exports_field/compatibility.mjs
- tools/package_json_rewriter/transformer/add_exports_field/public_api.mjs
- tools/parse_argv.mjs
- tools/test_esmodule_path_rewrite.mjs
- tools/test_package_contains_expected_all.mjs
- tools/test_package_exports.mjs
- Depend on https://github.com/karen-irc/option-t/pull/1126
> Use `node:` prefixed path to import Node.js' builtin modules

- src/shared/Function.ts
> Fix the link comment of `RecoveryWithErrorFn` in `./shared/Function`

- src/Maybe/andThen.ts
- src/Nullable/andThen.ts
- src/Nullable/andThenAsync.ts
- src/Nullable/orElse.ts
- src/PlainOption/andThen.ts
- src/PlainOption/orElse.ts
- src/PlainResult/andThen.ts
- src/PlainResult/andThenAsync.ts
- src/PlainResult/orElse.ts
- src/PlainResult/orElseAsync.ts
- src/Undefinable/andThen.ts
- src/Undefinable/orElse.ts
- src/shared/Function.ts
These are misintroduced types and provide alternatives for smooth migration. 
We should remove them.
> Remove all deprecated type alias that are provided alternatives

- src/PlainResult/index.ts
- tools/public_api/table.mjs
We should expose more explicit named APIs.
> Expose `expectIsOk` & `expectIsErr` from `option-t/PlainResult`

- __tests__/PlainOption/object_shape.test.mjs
- __tests__/PlainResult/object_shape.test.mjs
- src/PlainOption/Option.ts
- src/PlainResult/Result.ts
This is just **Breaking Change**.
With Next.js v12.1, we cannot use `PlainResult` type as the returned type for `getServerSideProps()` by following error.
```
Server Error
Error: Error serializing `.val` returned from `getServerSideProps` in "/path/[bafoo]".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
This error happened while generating the page. Any console logs will be displayed in the terminal window.
```
To avoid this error, an user need to re-implement `createOk`/`createErr`.
Next.js is emerging web development framework and I think it's important for next 3~5 years.
So we should fix them.
I confirmed what this change impacts on JSVM's internal shape (SM)/hidden class (V8)/structure (JSC).
I tested JavaScriptCore (for Safari 15.4), …
> Fill unused field for shape stability of `PlainResult<T, E>` type with `null` instead of `undefined`

- .github/workflows/publish_package_to_npm.yml
By documents, `released` event is dispatched even if we change pre-release to release.
I think this is more better for our workflow.
- https://docs.github.com/en/github-ae@latest/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#release
- https://docs.github.com/en/github-ae@latest/actions/using-workflows/events-that-trigger-workflows#release
> Use `released` event to invoke the workflow to publish to npm.

- src/PlainOption/Option.ts
- src/PlainResult/Result.ts
We changed the type of `PlainResult` and `PlainOption` by #1256 (this patch is included in v31). But that change disallowed to accept a value created by the v30 or prior versions  **on type level**.
This mean that the following code should work well on the running time but typescript compiler throw an type level incompatibility error if a user project enabled `--exactOptionalPropertyTypes` option.
```typescript
// This is type definition for v30 or former version.
type PaddingValueType = undefined;
type OldOk<T> = {
ok: true;
val: T;
err?: PaddingValueType;
};
type OldErr<E> =  {
ok: false;
val?: PaddingValueType;
err: E;
};
type OlderResult<T, E> = OldOk<T> | OldErr<E>;
declare const olderResult: OlderResult<string, Error>;
// typescript compiler will fail at here …
```
> Improve the backward compatibility with v30 or former version

- src/PlainResult/expect.ts
- src/PlainResult/unwrap.ts
This moves the position of deprecated functions to the bottom part of their files.
> Reorder the position of functions for unwrap/expect of `PlainResult`

- Makefile
This simplify the task naming.
> Rename `make distribution` to `make build`

- README.md
We deprecate these style import path newly.
- `option-t/cjs/**`
- `option-t/esm/**`
This does not mean that we remove these path but we recommend to use more modern import path.
Additionally, we abandon #808 for backward compatibility and for smooth migration.
> Mark `option-t/cjs` and `option-t/esm` path style as deprecated

- docs/idiom/README.md
- docs/idiom/unwrap_ok_or_throw_err.md
- tools/pkg_files.json
> Add idiom doc about "Unwrap if _result_ is `Ok(T)`, otherwise throw an inner value of `Err(E)`"

- .github/workflows/ci_on_main.yaml
We don't deploy in our main branch CI workflow.
So we don't have to do limit its concurrency.
> Remove the CI workflow concurrency restriction for main branch

- .github/workflows/_ci.yaml
- .github/workflows/ci_for_pr.yaml
- .github/workflows/ci_on_main.yaml
We don't deploy in our main branch CI workflow. We don't have to do limit its concurrency.
This tris #1388 again.
> Allow to run CI workflow for main branch concurrently

- package.json
- tools/cp_files.mjs
- tools/extension_renamer.mjs
- tools/generate_import_path_list_markdown.mjs
- tools/package_json_rewriter/main.mjs
- tools/test_esmodule_path_rewrite.mjs
- tools/test_package_contains_expected_all.mjs
- yarn.lock
[Node v16.17 also supports `parseArgs()`](https://nodejs.org/uk/blog/release/v16.17.0/). It's the time to switch it.
> Remove `@pkgjs/parseargs`

- .eslintrc.cjs
- package.json
This reverts commit d78460aa907f4c1ea19622b9ae5c94a6b4d976d0. #1409
If we set `type` in package.json to `module`, an user project which uses typescript with `moduleResolution=node16` will cause an type resolution error.
I guess tsc has some bugs. So we need to workaround.
Reopen https://github.com/karen-irc/option-t/issues/816
> Revert d78460a

- src/ClassOption/ClassicOption.d.ts
- src/ClassResult/ClassicResult.d.ts
This bug was introduced in 4c31b67e68d4a6e1adde989fbd23fee810bdcfa6 (#905)
> Fix the regression: import some types from ClassicOption.d.ts corrrectly

- package.json
We don't provide to allow to import `option-t` for a long time. So we should remove it.
> Remove `typings` field from package.json

- package.json
- yarn.lock
https://devblogs.microsoft.com/typescript/announcing-typescript-4-9-rc/
This tsc introduces [Decorators proposal's `accessor` syntax](https://github.com/tc39/proposal-decorators) and it will be emit to d.ts.
However, I don't think it (this commit) causes breaking change directly. Followings are reasons:
1. `accessor` is not allowed with target=ES5. We need to mark it as a breaking change if we bump up it.
2. Accepting `accessor` syntax will change type's shape. It also would be a breaking change individually.
> Update TypeScript compiler to 4.9 (RC)

- __tests__/PlainResult/try_catch_async.test.mjs
- src/PlainResult/tryCatchAsync.ts
`tryCatchIntoResultAsync()` accepts all functions returns `Promise<T>` regardless of normal (sync) function or async function.
For async function, all thrown error will be a rejected promise as
returned value.
But for normal function which is just return `Promise` object,
thrown error which is before return some values will be a simple thrown error.
This means the following code will throw an error on the current code base.
```js
// This _result_ should be expected as `Err(E)` but this code simply throw an error.
const result = tryCatchIntoResultAsync(() => {
throw new Error();
return Promise.resolve('bar');
})
```
So we should catch it.
> tryCatchIntoResultAsync() should catch an error thrown before normal (sync) fn `producer` returning a value

- __tests__/PlainResult/try_catch/try_catch.test.mjs
- __tests__/PlainResult/try_catch/try_catch_with_ensure_error.test.mjs
- __tests__/PlainResult/try_catch_async/try_catch_async.test.mjs
- __tests__/PlainResult/try_catch_async/try_catch_with_ensure_error_async.test.mjs
- src/PlainResult/tryCatch.ts
- src/PlainResult/tryCatchAsync.ts
- src/internal/assert.ts
- tools/public_api/table.mjs
This attempt to fix #1357.
Originally, I had planed to introduce an operator that returning `Result<T, Error>` from try-catch statement without checking a thrown value in #1357. But it's pattern is not a type safe.
I think this package should provide a type safe API first (and it's most common use case).
For the future, we may introduce `unsafeTryCatchIntoResult()` without checking to ensure `Error`.
> Implement `tryCatchIntoResult()` + ensure thrown value is `Error` instance

- .github/actions/prepare_ci/action.yaml
see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Remove `::set-output` usage in GH Action

- tools/package_json_rewriter/transformer/add_exports_field/ExportEntry.mjs
> Note that the "types" condition should always come first in "exports".
> https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing
> Fix the order of conditions in `exports` field in package.json

- tools/package_json_rewriter/transformer/add_exports_field/ExportEntry.mjs
- tools/test_package_json_exports_field_format.mjs
Retry #1522
---
By the blog,
https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing
We need do these things:
1. `types` condition should always come first.
2. `import` and `require` should be condition object.
> Fix the order of `types` condition in exports field in package.json

- Makefile
- package.json
- tools/babel/babelrc.d.cts.mjs
- yarn.lock
This fix a regression since e3601aa4ffa3b6468eccbff497c31d20539ad94a.
The regression causes some not intuitive type resolution error.
> Fix a regression: Fail to import `.d.cts` from other `.d.cts`

- tools/babel/babel-plugin-modify-ext.mjs
Since 9ae75978b7e666b7a87f4400dafe94b08e0ff7ba,
`import type {} from '...';` statement in d.cts will be transformed to `import {} from '...';` statement.
This is not a regression but it causes a bit difference between d.cts and d.ts. So this patch fix it.
> Preserve `import type {} from ...` syntax for d.cts

- src/PlainOption/Option.ts
- src/PlainResult/Result.ts
This deprecates these properties and recommend to use _unwrap_ operator instead.
- `PlainOption.val`
- `PlainResult.val`
- `PlainResult.err`
Historically, their type ware created to target a JSVM that supports ES5. Then there was no well optimized `Symbol` to achieve a private property.
We don't have a plan to change this into private property keep the backward compatibility.
> Mark data hold properties of PlainOption/PlainResult as deprecated

- README.md
- src/PlainOption/Option.ts
In JavaScript world, simple nullable type is better to express an absence of a value than this kind of tagged union type. 
`T | null` or `T | undefined` are common idiom for almost use-cases, are interoperable, and make a thing simple. Furthermore we provide a utility toolkit for their types.
This kind of type is still useful to contains null or undefined as not an absence value. But it’s a rare case. There is no reason to recommend to use it in general use cases.
Thus, now, we stop to recommend to use this and mark it as deprecated.
This does not mean that we remove this type in near future. It’s just to draw down from a recommended types.
Probably we will not be able to remove this for backward compatibility. Furthermore, it would not be costly to keep this type because:
1. This type …
> Mark PlainOption as "weak" deprecated

- src/Option.ts
- src/Result.ts
- tools/package_json_rewriter/transformer/add_exports_field/compatibility.mjs
- tools/public_api/table.mjs
By this change, we make these path deprecated to import a legacy wrapper object
- `lib/Option`
- `lib/Result`.
> Expose `lib/ClassicOption` and `lib/ClassicResult`

- src/PlainOption/Option.ts
- src/PlainResult/Result.ts
- src/PlainResult/unwrapOrThrowError.ts
They were introduced since fc6d10a05fe67ec8ed486c617e945bbb806b6c94.
I thought we should recommend to use operator functions,
but their deprecation marking is confusing
for a 3rd party user that uses a value returned from our user project.
Such 3rd party user would not install this package,
but then they need to handle their members with deprecation warnings.
It's not friendly behavior.
It's marked as `@deprecated` since 2067d466d6097f4bc0bfc9cfa11ec8f9dbc55e88.
After some considerations, we conclude that we don't recommend to use it, but we do not have to mark this as deprecated too.
> Remove some deprecations

- __tests__/PlainOption/as_mut.test.mjs
- __tests__/PlainOption/drop.test.mjs
- __tests__/PlainResult/as_mut.test.mjs
- __tests__/PlainResult/drop/test_drop_both.test.mjs
- __tests__/PlainResult/drop/test_drop_err.test.mjs
- __tests__/PlainResult/drop/test_drop_ok.test.mjs
- src/PlainOption/asMut.ts
- src/PlainOption/drop.ts
- src/PlainResult/asMut.ts
- src/PlainResult/drop.ts
- src/internal/ErrorMessage.ts
- src/internal/assert.ts
If the input is frozen, that's function will not work well. We should throw an error about it to notice the situation to user.
This change the behavior of function, but I think this is not a braking change because of that it would throw an error in another place if the passed value is frozen in this function's situation. This is just an early error.
> asMut should check whether the passed value is frozen

- .github/workflows/_ci.yaml
the error is:
```
git checkout HEAD -- /__w/option-t/option-t/package.json /__w/option-t/option-t/yarn.lock
fatal: detected dubious ownership in repository at '/__w/option-t/option-t'
To add an exception for this directory, call:
git config --global --add safe.directory /__w/option-t/option-t
```
I try to fix this by changing the command to simple `git reset --hard`.
> Fix CI fatal error for `make test_package_install` job

- packages/option-t/src/ClassicOption/ClassicOption.js
- packages/option-t/src/ClassicResult/ClassicResult.js
This is required for https://github.com/karen-irc/option-t/issues/1236
We shifted to ES6 class constructor since c8752a4493b081bc24d07e00fd1569ed91f4b19a.
However, in ES6 class, the following pattern is an error. We should back to ES5.
```js
class A {}
A.prototype = {};
```
> Back `Classic*` to to ES5 class idiom to avoid test errors

- Makefile
- packages/option-t/Makefile
This regression happens since  v33.5.3 b47c5b21752b61285e07327b59e076de2863e60e
> Fix the regression: the published package does not contain any docs

- packages/option-t/src/PlainResult/index.ts
We need this to do https://github.com/karen-irc/option-t/issues/1568
> Deprecate `toOptionFromOk()` & `toOptionFromErr()` which are exported  from `PlainResult/index`

- packages/option-t/src/PlainOption/compat/v33.ts
- packages/option-t/src/PlainOption/index.ts
- packages/option-t/src/PlainResult/compat/v33.ts
- packages/option-t/src/PlainResult/index.ts
> Mark `and`/`equal`/`or` that are exported by `Plain{Option,Result}/index` deprecated

- packages/option-t/tools/babel/babelrc.cjs.mjs
Fix #1519
We'd like to simplify an generated code. We think this would not be impactful because ES Module is common way now.
> Do not emit `exports.__esModule` for commonjs

- README.md
We plan to remove the support for it in the next (v35 or later) major release.
> Deprecate the support for TypeScript's `--moduleResolution node`

- README.md
- docs/how_to_import.md
- docs/public_api_list.md
- packages/option-t/tools/generate_import_path_list_markdown.mjs
`option-t/lib` was a migration compat path to do same thing as dual exports with tsc's `--moduleResolution node` (or `node10`).
Now, we drop to support its style completely. We should drop to mention about it from our docs.
> Drop to mention about `option-t/lib`

- packages/option-t/src/plain_option/index.ts
- packages/option-t/src/plain_option/namespace.ts
see https://github.com/option-t/option-t/pull/1535
> Add `deprecated` jsdoc tag to `PlainOption/index` and `PlainOption/namespace`

- packages/option-t/src/nullable/map_or_async.ts
We missed this annotation for a long time...
This would not be a breaking change because it would be an error even if we pass `null`.
> Annotate `NotNull<T>`  for `Nullable/mapOrAsync`

- README.md
- docs/deprecated_apis.md
We deprecated `PlainOption` weakly in #1535 (released in [v33.2.0](https://github.com/option-t/option-t/releases/tag/v33.2.0)).
This API still useful if you would like to contain a null value as a some value (e.g. `Some<null | undefined>`).
However, I think it's rare case in JavaScript generally.
At this time, we mark it deprecated officially. **This does not mean that we remove this API.**
> Deprecate `PlainOption<T>` officially

- README.md
- packages/option-t/tools/babel/babelconfig.mjs
- packages/option-t/tsconfig.json
Fix https://github.com/karen-irc/option-t/issues/1236
We choose ES2017 because:
1. We use `exports` in pacakge.json heavily. This feature is supported since Node.js v12.
We need choose Node.js v12 or earlier.
2. We would like to use async function without any down level transform.
3. We would like to keep syntax level change minimally.
> Change the compile target to ES2017

- packages/option-t/package.json
1. We use `exports` field heavily, so we should set it.
2. ava 5.2 only supports `>=14.19`. So we cannot support v12 even if they supports `exports`.
Fix https://github.com/karen-irc/option-t/issues/1527
> Set `>=14.21` to `engines` field of package.json

- packages/api_tests/__tests__/plain_result/try_catch/try_catch_with_ensure_error.test.mjs
- packages/api_tests/__tests__/plain_result/try_catch_async/try_catch_with_ensure_error_async.test.mjs
- packages/api_tests/__tests__/plain_result/unwrap_or_throw_error.test.mjs
- packages/option-t/src/internal/assert.ts
This relaxes the problem of that `String(input)` fails by `input` has `.toString()` but it fails.
Essentially, this is not our business. It would be  But we need to do this to avoid changes both of behavior and host environment requirement.
> Add the fallback path for `String(input)` failure in `assertIsErrorInstance()`

- packages/api_tests/__tests__/plain_result/try_catch/without_error_cause_support.test.mjs
- packages/api_tests/__tests__/plain_result/try_catch_async/without_error_cause_support.test.mjs
- packages/api_tests/__tests__/plain_result/unwrap_or_throw_error_without_error_cause_support.test.mjs
- packages/option-t/src/internal/assert.ts
- packages/option-t/src/plain_result/unwrap_or_throw_error.ts
I prefer this solution than #1831.
Fix #1832
[Why we call `String(input)` in `assertIsErrorInstance()`](https://github.com/option-t/option-t/blame/18b119a2bab1bda6c68e845a544efa523d243994/src/internal/assert.ts#L15-L16) is to improve debuggability on devtools. But I slacked to implement it with some compat path with `Error.cause`. As the result, we need to create a patch as #1831.
This patch rewrite the path for non `Error` instance in `assertIsErrorInstance()` with implementing `Error.cause` polyfill (Of cource we would like to remove it in #1833).
This simplify the implementation and take more standard like way.
This path is a fallback path for the place which we expect coming an  `Error` instance. I think we can allow some slow down.
This is a pain point but I think this would not be …
> Set `Error.cause` in `assertIsErrorInstance()` by hand if it is not implemented by the host environment

- packages/api_tests/__tests__/plain_result/try_catch/try_catch_with_ensure_error.test.mjs
- packages/api_tests/__tests__/plain_result/try_catch/without_error_cause_support.test.mjs
- packages/api_tests/__tests__/plain_result/try_catch_async/try_catch_with_ensure_error_async.test.mjs
- packages/api_tests/__tests__/plain_result/try_catch_async/without_error_cause_support.test.mjs
- packages/api_tests/__tests__/plain_result/unwrap_or_throw_error.test.mjs
- packages/api_tests/__tests__/plain_result/unwrap_or_throw_error_without_error_cause_support.test.mjs
By fc83496a090d6f10d78361e6736d5d40a9c2faae, we shifted to use `Error.cause` instead of calling `String(value)`.
Thus we don't have to keep them
> Remove unnecessary tests about calling `.toString()` and fail it in `assertIsErrorInstance()`

- .github/actions/prepare_ci/action.yaml
- .github/workflows/_ci.yaml
This improves the CI workflow running time from [4m54s](https://github.com/option-t/option-t/actions/runs/4595920606/usage) to [3m55s](https://github.com/option-t/option-t/actions/runs/4596720291/usage). Each of jobs improves their startup times about 10sec.
This try again https://github.com/option-t/option-t/pull/681
> Use actions/setup-node instead of running everything in the docker container.

- .github/workflows/publish_package_to_npm.yaml
- packages/option-t/Makefile
see:
- https://docs.npmjs.com/cli/v9/commands/npm-publish#provenance
- https://docs.npmjs.com/generating-provenance-statements
- https://github.blog/2023-04-19-introducing-npm-package-provenance/
> Generate provenance statements by npm cli's `--provenance` option

- package-lock.json
- package.json
We don't mark this commit as a breaking change due to their release note: https://devblogs.microsoft.com/typescript/announcing-typescript-5-1/
> Update TypeScript to 5.1

- .github/dependabot.yml
For our dependencies, weekly is a bit noisy.
> Switch dependabot's interval to monthly

- .github/workflows/ci_on_main.yaml
We're experimenting the merge queue.
see:
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group
- https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
> CI: Enable `merge_group` event for merge queue

- .github/workflows/ci_for_merge_queue.yaml
see:
> https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group
> 
> More than one activity type triggers this event. Although only the checks_requested activity type is supported, specifying the activity type will keep your workflow specific if more activity types are added in the future.
> ci: Run merge queue check only `merge_group` & `checks_requested` tyes for future change.

- eslint.config.js
- packages/option-t/tools/public_api/exposed_path.mjs
- packages/option-t/tools/public_api/mod.mjs
- tools/eslint/javascript.js
- tools/eslint/linter_option.js
- tools/eslint/typescript.js
- tools/eslint/vendor/eslintrc_core.cjs
In JavaScript, it's hard to minify a property that is on prototype chain. Typically, they appears as a pattern as class' instance method. We cannot remove or mangle a code like `a.foo()` style code without analysis for whole of programs including usages of reflection or identifying what item is a part of public interface.
This rule bans a class instance method that does not touch any `this` to improve a possibility to minify a code.
Additionally, after ES Module or CommonJS era (single module per single file), excluding the case to improve an API ergonomics or requirement to implement an object interface, we don't have to belong a function that does not touch `this` to a class as like as Java or C++.
To get a chance to improve a code size performance, it's better that we should export a …
> Enable ESLint's `class-methods-use-this` rule

- package-lock.json
- package.json
- packages/option-t/tools/cp_files.mjs
macOS & APFS supports Copy-on-Write file operation via clonefile system call.
However, Node.js builtin `fs.copyFile()` does not support its syscall for a long time.
To avoid it and improve our build efficiency, we use a pnpm's approach that uses [`@reflink/reflink`](https://www.npmjs.com/package/@reflink/reflink). 
This code path is still only enabled for macOS.
> Use reflink to copy files on macOS

- tools/eslint/vendor/eslintrc_core.cjs
- tools/eslint/vendor/eslintrc_typescript.cjs
https://eslint.org/blog/2023/10/deprecating-formatting-rules/
> Cleanup deprecated announced ESLint rules

- .github/dependabot.yml
This tries to fix dependabot watching. 
I guess dependabot cannot work correctly if we miss the trail `/`.
> Fix the path config for dependabot's `.github/actions/prepare_ci` watching

- eslint.config.js
- packages/option-t/tools/babel/babelrc.cjs.mjs
- packages/option-t/tools/babel/babelrc.d.cts.mjs
- packages/option-t/tools/extension_renamer.mjs
- packages/option-t/tools/generate_import_path_list_markdown.mjs
- packages/option-t/tools/package_json_rewriter/main.mjs
Reverts option-t/option-t#1990
vscode 1.86 still uses Node.js 18.17.1. ESLint extensions would not work if we use them.
> Revert "tools: Use `import.meta.filename` & `import.meta.dirname`"

- .github/workflows/_ci.yaml
This removes the dependency for `actions/github-script`
https://docs.github.com/en/actions/learn-github-actions/expressions
> ci: Stop to use `actions/github-script` for sentinel job

- README.md
- docs/how_to_import.md
We designed `option-t/<TypeName>/namespace` to allow to use  intellisense friendly (& some redundants) but we don't talk about it in anywhere of documents. Let's add the example for it.
> Add examples to import `option-t/<TypeName>/namespace`

- packages/option-t/src/maybe/index.ts
- packages/option-t/src/maybe/namespace.ts
- packages/option-t/src/nullable/index.ts
- packages/option-t/src/nullable/namespace.ts
- packages/option-t/src/plain_option/index.ts
- packages/option-t/src/plain_option/namespace.ts
- packages/option-t/src/plain_result/index.ts
- packages/option-t/src/plain_result/namespace.ts
- packages/option-t/src/undefinable/index.ts
- packages/option-t/src/undefinable/namespace.ts
To keep a simple API set, we don't expose APIs from there that takes multiple values to compose a data flow pipeline. We may reconsider it if pipeline operator syntax proposal is advanced to the standard.
- Fix #2049
- Fix #2051
- Fix #2051
- Fix #2052
- Fix #2054
- Fix #2055 
- Fix #2056
- Fix #2057
- Fix #2058
- Fix #2059
- Fix #2060
- Fix #2061
- Fix #2063
- Fix #2067
- Fix #2071
- Fix #2072
- Fix #2073
- Fix #2074
- Fix #2084
- Fix #2085
- Fix #2086
- Fix #2087
- Fix #2088
- Fix #2089
- Fix #2090
- Fix #2091
- Fix #2095
- Fix #2096
- Fix #2097
- Fix #2098
- Fix #2099
- Fix #2105
- Fix #2108
- Fix #2112
- Fix #2117
> Add comments about why we don't expose operators to compose a data flow from each of root endpoints.

- packages/option-t/src/maybe/namespace.ts
- packages/option-t/src/nullable/namespace.ts
- packages/option-t/src/plain_option/namespace.ts
- packages/option-t/src/plain_result/namespace.ts
- packages/option-t/src/undefinable/namespace.ts
This follows up https://github.com/option-t/option-t/issues/2173
> Add why we don't export self type as `Type` from `<TypeName>/namespace`

- package.json
- packages/option-t/src/maybe/namespace.ts
- packages/option-t/src/nullable/namespace.ts
- packages/option-t/src/plain_option/namespace.ts
- packages/option-t/src/plain_result/namespace.ts
- packages/option-t/src/undefinable/namespace.ts
- packages/option-t/tools/babel/babelrc.cjs.mjs
- pnpm-lock.yaml
That is defined in ES2020. We still use ES2015 as a module format.
This do https://github.com/option-t/option-t/pull/362 again.
> Stop `export * as ns` syntax

- packages/option-t/src/plain_option/option.ts
- packages/option-t/src/plain_result/result.ts
This fix the mismatch between actual value and types.
> Make types both `Err.val` & `Ok.err` to `null`

- README.md
- package.json
- packages/option-t/src/maybe/namespace.ts
- packages/option-t/src/nullable/namespace.ts
- packages/option-t/src/plain_option/namespace.ts
- packages/option-t/src/plain_result/namespace.ts
- packages/option-t/src/undefinable/namespace.ts
- packages/option-t/tools/babel/babelrc.cjs.mjs
- pnpm-lock.yaml
We expect recent bundlers supports it for a long time ago. It's the time to shift now.
> Use ES2020 as our ESM format

- .github/workflows/_ci.yaml
We moved all import behavior tests to unittest.
We don't have to run others with multiple Node.js
> Remove redundant CI matrix

- packages/api_tests/__tests__/cross_realm_error_helper.mjs
- packages/api_tests/__tests__/plain_result/try_catch/try_catch_with_ensure_error.test.mjs
- packages/api_tests/__tests__/plain_result/try_catch_async/try_catch_with_ensure_error_async/producer_is_async_fn.test.mjs
- packages/api_tests/__tests__/plain_result/try_catch_async/try_catch_with_ensure_error_async/producer_is_normal_fn.test.mjs
- packages/api_tests/__tests__/plain_result/unwrap_or_throw/throw_error_with_assert.test.mjs
- packages/option-t/src/internal/error_message.ts
- packages/option-t/src/plain_result/try_catch.ts
- packages/option-t/src/plain_result/try_catch_async.ts
- packages/option-t/src/plain_result/unwrap_or_throw_error.ts
By the current design, these APIs are not works expectedly since we rely on `value instanceof Error` heavily in their internals if they deal with cross-[realm](https://tc39.es/ecma262/2024/multipage/executable-code-and-execution-contexts.html#realm) `Error` instance (e.g. `node:vm`, iframe, mis-implementation).
- `tryCatchIntoResultWithEnsureError()`
- `tryCatchIntoResultWithEnsureErrorAsync()`
- `unwrapOrThrowWithEnsureErrorForResult()`
For a long term, we can expect [Error.isError](https://github.com/tc39/proposal-is-error) should be a part of ECMA262 but it has a long way to go...
- https://github.com/option-t/option-t/issues/2286
> Add testcases for dealing with cross-relam `Error` instance to `tryCatchIntoWithEnsureError` & `unwrapOrThrowWithEnsureError`

- docs/public_api_list.md
- packages/option-t/tools/public_api/table.mjs
This follows up https://github.com/option-t/option-t/pull/2280
> Mark `plain_result/unwrap_or_throw_error` & `plain_result/unwrap_or_throw_unknown` as deprecated in docs/public_api_list.md

- .vscode/settings.json
That is deprecated since vscode-eslint 3.0.5 or later:
> There is a new `eslint.useFlatConfig`` setting which is honored by ESLint version 8.57.0 and above.
> If one of those versions is used, the extension adheres to the ESLint Flat config rollout plan.
> The setting has the same meaning as the environment variable `ESLINT_USE_FLAT_CONFIG`.
https://github.com/microsoft/vscode-eslint/tree/4b202340da986fec4f926e72312508e20b2140f0
> Remove `eslint.experimental.useFlatConfig setting`

- package.json
- pnpm-lock.yaml
According to the release blog,
we would be able to update TypeScript without the breaking change release of ourselves.
https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/
Fix https://github.com/option-t/option-t/issues/2294
> Update TypeScript to 5.5

- package.json
- pnpm-lock.yaml
- tsconfig.base.json
https://devblogs.microsoft.com/typescript/announcing-typescript-5-6/
By the document, this release would not be a breaking change.
> Update typescript to v5.6

- packages/api_tests/__tests__/plain_option/transpose/to_plain_option.test.mjs
- packages/api_tests/__tests__/plain_option/transpose/to_result.test.mjs
- packages/api_tests/__tests__/plain_result/and.test.mjs
- packages/api_tests/__tests__/plain_result/and_then.test.mjs
- packages/api_tests/__tests__/plain_result/and_then_async.test.mjs
- packages/api_tests/__tests__/plain_result/create.test.mjs
- packages/api_tests/__tests__/plain_result/drop/test_drop_both.test.mjs
- packages/api_tests/__tests__/plain_result/drop/test_drop_err.test.mjs
- packages/api_tests/__tests__/plain_result/drop/test_drop_ok.test.mjs
- packages/api_tests/__tests__/plain_result/flatten.test.mjs
- packages/api_tests/__tests__/plain_result/map.test.mjs
- packages/api_tests/__tests__/plain_result/map_async.test.mjs
- packages/api_tests/__tests__/plain_result/map_err.test.mjs
- packages/api_tests/__tests__/plain_result/map_err_async.test.mjs
- packages/api_tests/__tests__/plain_result/or.test.mjs
- packages/api_tests/__tests__/plain_result/transpose/to_nullable.test.mjs
- packages/api_tests/__tests__/plain_result/transpose/to_undefinable.test.mjs
For the future refactoring #2244, we change to avoid touch object properties directly.
> Use public API as possible for testing for plain result

- packages/api_tests/__tests__/exposed_path/helper.mjs
This test same module is loaded if the module system recognize `module-sync`
see https://github.com/option-t/option-t/issues/2380
> Add tests that checks loads actual same module via `import()` and `require()`

- .github/workflows/_ci.yaml
https://nodejs.org/en/blog/release/v23.0.0
> ci: Add Node v23 for unint test job

- README.md
This explains what I would like to say in https://github.com/option-t/option-t/issues/2328
> Add why we don't provide `try!` like control flow sugar utility to README

- tools/publish/.npmrc
This option was removed since v7
https://docs.npmjs.com/cli/v6/using-npm/config
> Remove unnecessary `always-auth` from .npmrc

- tools/eslint/vendor/eslintrc_typescript.cjs
https://typescript-eslint.io/rules/no-redeclare/
> Disable ESLint's no-redeclare rule for typescript

- package.json
pnpm v10.x is try to not executed a lifecycle script during installation by default without allowlist.
I think this mitigation would be helpful to secure our development.
https://github.com/pnpm/pnpm/releases/tag/v10.0.0-rc.3
> Use pnpm v10.x to prevent to mitigate the attack caused by a malicious lifecycle script.

- package.json
- pnpm-lock.yaml
- tsconfig.base.json
This has a potentially breaking change:
> https://devblogs.microsoft.com/typescript/announcing-typescript-5-8/
>
> **Preserved Computed Property Names in Declaration Files**
> Note that it’s possible (though unlikely) that a file compiled in TypeScript 5.8 may generate a declaration file that is not backward compatible in TypeScript 5.7 or earlier.
> Upgrade TypeScript to 5.8 

- packages/api_tests/__tests__/exposed_path/helper.mjs
This follows up https://github.com/option-t/option-t/pull/2266
> Remove test hack checks `process.features.require_module` to enable `require(esm)`

- .github/workflows/_ci.yaml
We dropped to support for them in https://github.com/option-t/option-t/pull/2531
> ci: Drop legacy Node.js from unittest jobs

- .github/dependabot.yml
Fix https://github.com/option-t/option-t/issues/2570
This aims to mitigate a supply chain attack risk happens frequently recently. 1-week delay is judged by just my intuition as heuristic.
- https://github.blog/changelog/2025-07-01-dependabot-supports-configuration-of-a-minimum-package-age/
- https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates#setting-up-a-cooldown-period-for-dependency-updates
- https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#cooldown-
> dependabot: Add `cooldown` setting

- .github/actions/prepare_ci/action.yaml
- .github/workflows/publish_package_to_npm.yaml
- .gitignore
- Makefile
- tools/publish/.npmrc
By https://github.com/option-t/option-t/issues/2582, we can do this.
> Remove unnecessary npmrc copying step for publishing

- packages/option-t/src/maybe/compat/v54.ts
- packages/option-t/src/nullable/compat/v54.ts
- packages/option-t/src/plain_result/compat/v54.ts
- packages/option-t/src/undefinable/compat/v54.ts
I guess we cannot remove this module path  for backward compat...
> Remove `@deprecated` jsdoc tag from `option-t/<type_name>/compat/v54`
