- README.md
> Add Version Badge

- README.md
> Write more documents

- .gitignore
- option-t.d.ts
- package.json
- test/test_type_definition.ts
> Add the type definition.

- CHANGELOG.md
- README.md
- option-t.d.ts
- package.json
- src/OptionT.js
- src/OptionType.js
- src/index.js
- test/manifest.js
- test/old/test_drop.js
- test/old/test_flatmap.js
- test/old/test_initialize.js
- test/old/test_json.js
- test/old/test_map.js
- test/old/test_unwrap.js
- test/old/utils.js
- test/test_drop.js
- test/test_inheritance.js
- test/test_type_definition.ts
> Introduce Some<T> & None<T>.

- CHANGELOG.md
- option-t.d.ts
- src/OptionT.js
- test/test_type_definition.ts
- test/test_unwrap_or.js
> Implement Option<T>.unwrapOr().

- CHANGELOG.md
- option-t.d.ts
- src/OptionT.js
- test/manifest.js
- test/test_type_definition.ts
- test/test_unwrap_or_else.js
>  	Implement Option<T>.unwrapOrElse()

- CHANGELOG.md
- option-t.d.ts
- src/OptionT.js
- test/test_expect.js
- test/test_type_definition.ts
> Implement Option<T>.expect()

- CHANGELOG.md
- option-t.d.ts
- src/OptionT.js
- test/manifest.js
- test/test_map_or.js
- test/test_type_definition.ts
> Implement Option<T>.mapOr()

- CHANGELOG.md
- option-t.d.ts
- src/OptionT.js
- test/manifest.js
- test/test_map_or_else.js
- test/test_type_definition.ts
> Implement Option<T>.mapOrElse().

- CHANGELOG.md
- option-t.d.ts
- src/OptionT.js
- test/test_initialize.js
- test/test_type_definition.ts
> Implement Option<T>.isNone

- CHANGELOG.md
- src/OptionT.js
This stops to delay the next release which is blocked by https://github.com/saneyuki/option-t.js/pull/50.
> Mark mapOr/mapOrElse as experimental API.

- CHANGELOG.md
- README.md
- option-t.d.ts
- package.json
- src/OptionT.js
- test/manifest.js
- test/test_as_promise.js
- test/test_type_definition.ts
> Implement Option<T>.asPromise().

- option-t.d.ts
- tsconfig.json
> Fix the compiler error if we use tsc's '--noImplicitAny' flag.

- package.json
`tsd` and `dtsm` support discovery and linking of typescript definitions from packages installed with `npm` or `bower`.
To enable this function, this commit adds some metadata to `package.json`.
For more detail information, [please see the README of tsd](https://github.com/DefinitelyTyped/tsd#link-to-bundled-definitions)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/62)
> Support tsd/dtsm's link function

- package.json
We need to add @gifnksm as contributor by https://github.com/saneyuki/option-t.js/pull/62.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/63)
> Add @gifnksm as contributor to package.json.

- package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/64)
> Update ESLint v0.22.x

- CHANGELOG.md
- package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/65)
> Add keywords section to package.json

- package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/68)
> Update TypeScript to 1.5.3

- package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/70)
> Add typings field to package.json.

- CHANGELOG.md
fixup #70
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/71)
> Add changelog about #70

- .editorconfig
- CHANGELOG.md
- option-t.d.ts
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/75)
> Add API documentations to TypeScript's type definition.

- package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/80)
> Add 'engines' fields to package.json.

- CHANGELOG.md
- package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/76)
> Update TypeScript compiler to 1.6.0-beta.

- CHANGELOG.md
- option-t.d.ts
- This requires #76
- Follow up #77
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/81)
> Change `OptionBase` type definition to abstract class.

- CHANGELOG.md
- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/85)
> Add the reason to README.md that to expose 'OptionBase' to TypeScript

- .travis.yml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/89)
> Add NodeJS v5 to Travis

- .travis.yml
- CHANGELOG.md
- package.json
- test/manifest.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/90)
> Remove Node.js v0.10 from a CI tested environment

- CHANGELOG.md
- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/91)
> Polish the documentation about casting to Promise

- CHANGELOG.md
- option-t.d.ts
- option-t.es6.d.ts
- package.json
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/97)
> feat(Option<T>): define isSome/isNone as type guard.

- CHANGELOG.md
- package.json
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/98)
> chore(node): BREAKING CHANGE - Support only after NodeJS 4.2 LTS

- tools/whitespace.txt
Fix #100
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/102)
> chore(whitespace): test homu

- CHANGELOG.md
- option-t.d.ts
#103
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/104)
> fix(compile error): revert #97

- CHANGELOG.md
- option-t.d.ts
catch #104. #106
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/106)
> fix(d.ts): fix the compile error of option-t.d.ts

- package.json
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/107)
> chore(typescript): update to 1.8.2

- package.json
- test/.eslintrc.js
- test/option-t/test_and.js
- test/option-t/test_as_promise.js
- test/option-t/test_flatmap.js
- test/option-t/test_initialize.js
- test/option-t/test_map.js
- test/option-t/test_map_or.js
- test/option-t/test_map_or_else.js
- test/option-t/test_or.js
- test/option-t/test_or_else.js
- test/utils.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/110)
> test(ESLint): lint for test/ dir.

- test/option-t/test_and.js
- test/option-t/test_as_promise.js
- test/option-t/test_expect.js
- test/option-t/test_flatmap.js
- test/option-t/test_inheritance.js
- test/option-t/test_initialize.js
- test/option-t/test_json.js
- test/option-t/test_map.js
- test/option-t/test_map_or.js
- test/option-t/test_map_or_else.js
- test/option-t/test_or.js
- test/option-t/test_or_else.js
- test/option-t/test_unwrap.js
- test/option-t/test_unwrap_or.js
- test/option-t/test_unwrap_or_else.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/112)
> refactor(test): use  instead of 'ok()'

- test/.eslintrc.js
- test/option-t/test_and.js
- test/option-t/test_as_promise.js
- test/option-t/test_drop.js
- test/option-t/test_expect.js
- test/option-t/test_flatmap.js
- test/option-t/test_inheritance.js
- test/option-t/test_initialize.js
- test/option-t/test_json.js
- test/option-t/test_map.js
- test/option-t/test_map_or.js
- test/option-t/test_map_or_else.js
- test/option-t/test_or.js
- test/option-t/test_or_else.js
- test/option-t/test_unwrap.js
- test/option-t/test_unwrap_or.js
- test/option-t/test_unwrap_or_else.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/113)
> refactor(test): use const/let instead of var

- test/option-t/test_and.js
- test/option-t/test_as_promise.js
- test/option-t/test_drop.js
- test/option-t/test_expect.js
- test/option-t/test_flatmap.js
- test/option-t/test_inheritance.js
- test/option-t/test_initialize.js
- test/option-t/test_json.js
- test/option-t/test_map.js
- test/option-t/test_map_or.js
- test/option-t/test_map_or_else.js
- test/option-t/test_or.js
- test/option-t/test_or_else.js
- test/option-t/test_unwrap.js
- test/option-t/test_unwrap_or.js
- test/option-t/test_unwrap_or_else.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/114)
> refactor(test): import src file directly

- CHANGELOG.md
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/117)
> docs(CHANGELOG): add changelog from v0.16.3

- CHANGELOG.md
- option-t.d.ts
- src/OptionT.d.ts
- src/OptionT.js
- src/ResultTE.d.ts
- src/ResultTE.js
- test/option-t/test_drop.js
- test/option-t/test_type_definition.ts
- test/option-t/test_type_definition_es6.ts
- test/result-te/test_drop.js
- test/result-te/test_type_definition_es6.ts
Fix #87
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/118)
> feat(drop): Enable to take a custom destructor function to 'drop()' methods.

- test/option-t/test_initialize.js
- test/option-t/test_json.js
- test/result-te/test_initialize.js
- test/utils.js
Fix #86
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/121)
> test(utils): add ES6 collections to test.

- CHANGELOG.md
- src/Result.d.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/122)
> refactor(Result): rename internal types' naming in Result.d.ts

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/124)
> chore(package.json): update outdated packages

- CHANGELOG.md
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/126)
> doc(README): Add some semantics descriptions

- CHANGELOG.md
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/127)
> doc(README): add more descriptions about runtime nullability checking

- CHANGELOG.md
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/128)
> fix(README): fix the link to API documentations.

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/129)
> doc(CHANGELOG): add links to pull request

- CHANGELOG.md
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/130)
> fix(nit): fix the sample code of casting from Option<T> to Promise

- .eslintrc.js
- package.json
- src/Option.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/131)
> chore(package.json): update dependencies

- .editorconfig
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/134)
> chore(EditorConfig): enable insert_final_newline

- package.json
- src/.eslintrc.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/137)
> refactor(eslint): use 'commonjs' env instead of 'node'.

- .travis.yml
- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/136)
> chore(travis): enable node v6 as a targeted runtimed

- package.json
- test/.eslintrc.js
Fix the regression by #135
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/138)
> fix(eslint): lint .eslintrc.js correctly

- CHANGELOG.md
- option-t.d.ts
- package.json
- src/Option.d.ts
- src/Result.d.ts
- test/option-t/test_type_definition.ts
- test/option-t/test_type_definition_es6.ts
- tsconfig.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/141)
> chore(package.json): update typescript compiler to v2

- CHANGELOG.md
- option-t.d.ts
- src/Option.d.ts
- src/Result.d.ts
This change requires to use TypeScript 2.0 or highers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/142)
> refactor(typings): specify 'this' types for callbacks (BREAKING CHANGE)

- option-t.d.ts
- src/Option.d.ts
- src/Result.d.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/143)
> refactor(typings): use 'void' to specify 'this' type

- test/result-te/test_type_definition_es6.ts
- tsconfig.json
This also fixes the regression caused by https://github.com/saneyuki/option-t.js/pull/141
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/146)
> refactor(tsconfig.json): use glob.

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/147)
> chore(travis): use 'node' to specify the target version.

- CHANGELOG.md
- package.json
Regression by #145
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/149)
> fix(package.json): fix the list for packaged files

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/153)
> chore(package.json): update typescript compiler

- CHANGELOG.md
- src/Option.d.ts
- src/Result.d.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/154)
> refactor(typings): use 'never' type

- src/Option.d.ts
- src/Result.d.ts
see https://github.com/Microsoft/TypeScript/pull/9407
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/152)
> Use boolean literal types to represent our type

- README.md
- docs/IDIOM.md
- package.json
- Instead of prividing a new features, we provide some idioms as the document.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/159)
> Add the document about idioms

- package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/163)
> Upgrade dependencies to the latest

- CHANGELOG.md
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/164)
> Remove engines field from package.json

- CHANGELOG.md
- src/Nullable/Function.ts
- src/Nullable/index.ts
- src/Nullable/orElse.ts
- src/Undefinable/Function.ts
- src/Undefinable/index.ts
- src/Undefinable/orElse.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/170)
> default export orElse for Nullable/Undefinable

- .travis.yml
- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/173)
> Drop support for Node v4

- CHANGELOG.md
- tsconfig.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/174)
> Use es5 as a default target

- CHANGELOG.md
- src/Maybe/Maybe.ts
- test/Maybe/test_type_guard.js
- `Maybe::isUndefinedOrNull()` -> `Maybe::isNullOrUndefined()`
- `Maybe::isSomeActual()` -> `Maybe::isSomeValue()`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/176)
> Rename Maybe type guard

- test/option-t/test_initialize.js
- test/option-t/test_json.js
- test/result-te/test_initialize.js
- test/utils.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/179)
> Fix tests related to non-json-serializable builtin objects.

- CHANGELOG.md
- src/Maybe/Maybe.ts
- test/Maybe/test_type_guard.js
Make meaning more clearly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/184)
> Rename Maybe::isSomeValue() -> Maybe::isNotNullAndUndefined()

- CHANGELOG.md
- src/Maybe/ErrorMessage.ts
- src/Maybe/Function.ts
- src/Maybe/and.ts
- src/Maybe/andThen.ts
- src/Maybe/do.ts
- src/Maybe/expect.ts
- src/Maybe/index.ts
- src/Maybe/map.ts
- src/Maybe/mapOr.ts
- src/Maybe/mapOrElse.ts
- src/Maybe/or.ts
- src/Maybe/orElse.ts
- src/Maybe/unwrap.ts
- src/Maybe/unwrapOr.ts
- src/Maybe/unwrapOrElse.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/185)
> Implement more functions for Maybe namespace.

- CHANGELOG.md
- src/Maybe/unwrap.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/186)
> unwrapMaybe() should throw more detailed message.

- .eslintignore
- .gitignore
- CHANGELOG.md
- gulpfile.js
- package.json
- yarn.lock
https://github.com/saneyuki/option-t.js/issues/188
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/191)
> Add mjs to `es6/` dir

- .eslintignore
- .gitignore
- CHANGELOG.md
- gulpfile.js
- package.json
- tsconfig_esm.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/192)
>  Rename `option-t/es6` to `option-t/esm`

- CHANGELOG.md
- src/PlainOption/Option.ts
- src/PlainOption/index.ts
- src/PlainResult/Result.ts
- src/PlainResult/index.ts
- test/PlainOption/test_create.js
- test/PlainOption/test_type_guard.js
- test/PlainResult/test_create.js
- test/PlainResult/test_type_guard.js
- test/manifest.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/196)
>  Fix the serious bug isOk/isSome returns true if their input is not so. 

- CHANGELOG.md
- src/Option.d.ts
- src/Option.js
- test/option-t/test_drop.js
- test/option-t/test_initialize.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/195)
> Refactoring internal design for OptionT

- CHANGELOG.md
- src/PlainResult/do.ts
- src/PlainResult/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/197)
> Rethink PlainResult/do

- gulpfile.js
- package.json
- src/.eslintrc.js
- src/Option.js
- src/Result.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saneyuki/option-t.js/198)
> Remove to disable no-var for js files in src/

- CHANGELOG.md
- README.md
- docs/IDIOM.md
- package.json
- src/Option.d.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/199)
> Fix the repository links

- .travis.yml
see https://bors.tech/documentation/getting-started/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/203)
> Exclude bors-ng's working branch from TravisCI

- .travis.yml
- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/204)
> Drop to support Node v6 LTS

- .eslintrc.js
- tools/eslint/eslintrc_core.js
Import https://github.com/voyagegroup/eslint-config-fluct/blob/master/config/eslintrc_core.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/205)
> Import eslint-config-fluct's core ruleset

- gulpfile.js
- package.json
- src/Maybe/andThen.ts
- src/Nullable/andThen.ts
- src/Option.d.ts
- src/PlainResult/index.ts
- src/PlainResult/map.ts
- src/Result.d.ts
- src/Undefinable/andThen.ts
- src/index.d.ts
- tools/tslint/LICENSE.MIT
- tools/tslint/basic.json
- tools/tslint/typecheck.json
- tslint.json
- yarn.lock
This use https://github.com/voyagegroup/tslint-config-fluct
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/206)
> Introduce tslint 

- src/Nullable/and.ts
- src/Nullable/andThen.ts
- src/Nullable/do.ts
- src/Nullable/expect.ts
- src/Nullable/map.ts
- src/Nullable/mapOr.ts
- src/Nullable/mapOrElse.ts
- src/Nullable/or.ts
- src/Nullable/orElse.ts
- src/Nullable/unwrapOr.ts
- src/Nullable/unwrapOrElse.ts
This is just for perf.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/207)
> Inline isNull/isNotNull by hand to decrease calling a function

- CHANGELOG.md
- src/Undefinable/and.ts
- src/Undefinable/andThen.ts
- src/Undefinable/do.ts
- src/Undefinable/expect.ts
- src/Undefinable/map.ts
- src/Undefinable/mapOr.ts
- src/Undefinable/mapOrElse.ts
- src/Undefinable/or.ts
- src/Undefinable/orElse.ts
- src/Undefinable/unwrapOr.ts
- src/Undefinable/unwrapOrElse.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/209)
> Inline isUndefined/isNotUndefined by hand to decrease calling a function

- CHANGELOG.md
- src/PlainOption/and.ts
- src/PlainOption/andThen.ts
- src/PlainOption/do.ts
- src/PlainOption/expect.ts
- src/PlainOption/map.ts
- src/PlainOption/mapOr.ts
- src/PlainOption/mapOrElse.ts
- src/PlainOption/or.ts
- src/PlainOption/orElse.ts
- src/PlainOption/unwrapOr.ts
- src/PlainOption/unwrapOrElse.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/210)
> Inline isSome/isNone by hand to decrease calling a function

- CHANGELOG.md
- src/PlainResult/and.ts
- src/PlainResult/andThen.ts
- src/PlainResult/expect.ts
- src/PlainResult/map.ts
- src/PlainResult/mapErr.ts
- src/PlainResult/or.ts
- src/PlainResult/orElse.ts
- src/PlainResult/toOption.ts
- src/PlainResult/unwrapOr.ts
- src/PlainResult/unwrapOrElse.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/211)
> Inline isOk()/isErr() by hand to decrease calling a function

- CHANGELOG.md
- src/Maybe/and.ts
- src/Maybe/andThen.ts
- src/Maybe/do.ts
- src/Maybe/expect.ts
- src/Maybe/map.ts
- src/Maybe/mapOr.ts
- src/Maybe/mapOrElse.ts
- src/Maybe/or.ts
- src/Maybe/orElse.ts
- src/Maybe/unwrapOr.ts
- src/Maybe/unwrapOrElse.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/212)
> Inline isNotNullAndUndefined()/isNullOrUndefined() by hand to decrease calling a function

- CHANGELOG.md
- LICENSE.MIT
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/221)
> Add LICENSE.MIT

- .eslintignore
- .gitignore
- CHANGELOG.md
- README.md
- gulpfile.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/224)
> Publish lib/ directory which contains commonjs and esmodule. 

- .editorconfig
- CHANGELOG.md
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/225)
> Fix the indent problem in README.md 

- CHANGELOG.md
- docs/SEMANTICS.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/226)
> Sort indent with 4 for all markdown files

- CHANGELOG.md
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/227)
> Publish lib/ to npm correctly

- CHANGELOG.md
- src/Maybe/do.ts
- src/Maybe/index.ts
- src/Nullable/do.ts
- src/Nullable/index.ts
- src/PlainOption/do.ts
- src/PlainOption/index.ts
- src/PlainResult/do.ts
- src/PlainResult/index.ts
- src/Undefinable/do.ts
- src/Undefinable/index.ts
- src/utils/Function.ts
Fix https://github.com/karen-irc/option-t/issues/228
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/230)
> Remove obsoleted do()

- CHANGELOG.md
- src/Maybe/andThen.ts
- src/Maybe/orElse.ts
- src/Maybe/unwrapOrElse.ts
- src/Nullable/andThen.ts
- src/Nullable/orElse.ts
- src/Nullable/unwrapOrElse.ts
- src/Option.d.ts
- src/PlainOption/andThen.ts
- src/PlainOption/orElse.ts
- src/PlainResult/Function.ts
- src/PlainResult/andThen.ts
- src/PlainResult/orElse.ts
- src/Result.d.ts
- src/Undefinable/andThen.ts
- src/Undefinable/orElse.ts
- src/Undefinable/unwrapOrElse.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/223)
> Reorganize internal function types

- test/option-t/test_and.js
- test/option-t/test_flatmap.js
- test/option-t/test_initialize.js
- test/option-t/test_map.js
- test/option-t/test_or.js
- test/option-t/test_or_else.js
- test/result-te/test_initialize.js
This relates to https://github.com/karen-irc/option-t/issues/232
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/234)
> Stop to use 'instanceof' checking for testcases

- CHANGELOG.md
- src/PlainOption/Option.ts
- src/PlainResult/Result.ts
- test/PlainOption/test_object_shape.js
- test/PlainResult/test_object_shape.js
- test/manifest.js
This type optimization would be effective for some engines by using the same hidden class.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/231)
> Stabilize the shape for PlainOption<T>/PlainResult<T, E>

- src/Maybe/expect.ts
- src/Nullable/expect.ts
- src/Undefinable/expect.ts
- test/Maybe/test_expect.js
- test/Nullable/test_expect.js
- test/Undefinable/test_expect.js
- test/manifest.js
- test/utils.js
Fix https://github.com/karen-irc/option-t/issues/247
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/250)
> Stabilize expect() for Maybe/Nullable/Undefinable

- src/Maybe/unwrap.ts
- src/Nullable/unwrap.ts
- src/Undefinable/unwrap.ts
- test/Maybe/test_unwrap.js
- test/Nullable/test_unwrap.js
- test/Undefinable/test_unwrap.js
- test/manifest.js
Fix https://github.com/karen-irc/option-t/issues/240
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/251)
> Stabilize unwrap() for Maybe/Nullable/Undefinable

- src/Maybe/expect.ts
- src/Maybe/unwrap.ts
- src/Maybe/unwrapOr.ts
- src/Maybe/unwrapOrElse.ts
- src/Nullable/expect.ts
- src/Nullable/unwrap.ts
- src/Nullable/unwrapOr.ts
- src/Nullable/unwrapOrElse.ts
- src/Undefinable/expect.ts
- src/Undefinable/unwrap.ts
- src/Undefinable/unwrapOr.ts
- src/Undefinable/unwrapOrElse.ts
- test/Maybe/test_unwrap_or.js
- test/Maybe/test_unwrap_or_else.js
- test/Nullable/test_unwrap_or.js
- test/Nullable/test_unwrap_or_else.js
- test/Undefinable/test_unwrap_or.js
- test/Undefinable/test_unwrap_or_else.js
- test/manifest.js
- Fix https://github.com/karen-irc/option-t/issues/238
- Fix https://github.com/karen-irc/option-t/issues/239
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/253)
> Stabilize unwrapOr/unwrapOrElse for Maybe/Nullable/Undefinable

- package.json
- yarn.lock
Fix https://github.com/karen-irc/option-t/issues/237
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/255)
> Update typescript 2.7

- gulpfile.js
- tsconfig.json
- tsconfig_cjs.json
- tsconfig_esm.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/256)
> Reconfig tsconfig.json 

- .babelrc
- gulpfile.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/257)
> Remove needless .babelrc

- src/Maybe/andThen.ts
- src/Nullable/andThen.ts
- src/Undefinable/andThen.ts
- test/Maybe/test_and_then.js
- test/Nullable/test_and_then.js
- test/Undefinable/test_and_then.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/261)
> Stablize andThen for Maybe/Nullable/Undefinable

- src/Maybe/mapOr.ts
- src/Nullable/mapOr.ts
- src/Undefinable/mapOr.ts
- test/Maybe/test_map_or.js
- test/Nullable/test_map_or.js
- test/Undefinable/test_map_or.js
Fix https://github.com/karen-irc/option-t/issues/245
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/262)
> Stabilize mapOr for Maybe/Nullable/Undefinable

- src/Maybe/mapOrElse.ts
- src/Nullable/mapOrElse.ts
- src/Undefinable/mapOrElse.ts
- test/Maybe/test_map_or_else.js
- test/Nullable/test_map_or_else.js
- test/Undefinable/test_map_or_else.js
Fix https://github.com/karen-irc/option-t/issues/244
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/263)
> Stabilize mapOrElse for Maybe/Nullable/Undefinable

- src/Maybe/and.ts
- src/Nullable/and.ts
- src/Undefinable/and.ts
- test/Maybe/test_and.js
- test/Nullable/test_and.js
- test/Undefinable/test_and.js
Fix https://github.com/karen-irc/option-t/issues/249
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/265)
> Stabilize and() for Maybe/Nullable/Undefinable

- src/Maybe/or.ts
- src/Nullable/or.ts
- src/Undefinable/or.ts
- test/Maybe/test_and.js
- test/Maybe/test_or.js
- test/Nullable/test_and.js
- test/Nullable/test_or.js
- test/Undefinable/test_and.js
- test/Undefinable/test_or.js
Fix https://github.com/karen-irc/option-t/issues/243
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/266)
>  Stabilize or() for Maybe/Nullable/Undefinable 

- gulpfile.js
- package.json
- test_ava/test_example.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/258)
> Introduce avajs 

- CHANGELOG.md
- src/Maybe/tap.ts
- src/Nullable/tap.ts
- src/Undefinable/tap.ts
- test/Maybe/test_tap.js
- test/Nullable/test_tap.js
- test/Undefinable/test_tap.js
Fix https://github.com/karen-irc/option-t/issues/241
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/264)
> Stabilize tap for Maybe/Nullable/Undefinable

- CHANGELOG.md
- gulpfile.js
- package.json
- test_ava/test_example.js
- yarn.lock
This reverts commit 82e6f6ab58cc5b7e364b4fa84efa27270bcaf591, reversing
changes made to 757ad07bec40e4cc5b112e83c11bf54758e87400.
I don't seem this is not suite for our purpose.
This revert https://github.com/karen-irc/option-t/pull/258
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/269)
> Revert "Introduce ava"

- gulpfile.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/270)
> Add the gulp task to run mocha without power-assert

- src/Option.d.ts
- src/Option.js
- src/Result.d.ts
- src/Result.js
- test/option-t/test_create.js
- test/option-t/test_type_definition.ts
- test/result-te/test_create.js
- test/result-te/test_type_definition_es6.ts
As a migration plan for https://github.com/karen-irc/option-t/issues/232
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/235)
> Add factory function for lib/Option and lib/Result

- src/Maybe/tap.ts
- src/Nullable/tap.ts
- src/PlainOption/tap.ts
- src/PlainResult/tap.ts
- src/Undefinable/tap.ts
- test/Maybe/test_tap.js
- test/Nullable/test_tap.js
- test/PlainOption/test_tap.js
- test/PlainResult/test_tap.js
- test/Undefinable/test_tap.js
Fix https://github.com/karen-irc/option-t/issues/267
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/271)
> Return the input value on tap() for Maybe/Nullable/Undefinable/PlainOption/PlainResult

- src/Maybe/unwrapOr.ts
- src/Maybe/unwrapOrElse.ts
- src/Nullable/unwrapOr.ts
- src/Nullable/unwrapOrElse.ts
- src/Undefinable/unwrapOr.ts
- src/Undefinable/unwrapOrElse.ts
- test/Maybe/test_unwrap_or.js
- test/Maybe/test_unwrap_or_else.js
- test/Nullable/test_unwrap_or.js
- test/Nullable/test_unwrap_or_else.js
- test/Undefinable/test_unwrap_or.js
- test/Undefinable/test_unwrap_or_else.js
Fix https://github.com/karen-irc/option-t/issues/254
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/278)
> Assert the default value in unwrapOr/unwrapOrElse for Maybe/Nullable/Undefinable

- tools/eslint/eslintrc_core.js
- tools/tslint/basic.json
- tools/tslint/typecheck.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/279)
> Update Lint rules

- src/index.d.ts
- src/index.js
This follows up https://github.com/karen-irc/option-t/pull/235
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/283)
> index.js export factories for `lib/Option`

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/284)
>  Update README to express the current state 

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/285)
> Add more descriptions about PlainOption/PlainResult

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/286)
> Remove incomplete phrase from README

- src/Option.js
- src/Result.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/288)
> Use factory functions insteadof obsolete constructors

- .travis.yml
- Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/289)
> Define ci tasks in Makefile

- Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/290)
> Check git-diff in CI phase

- .editorconfig
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/291)
> Add Makefile to editorconfig

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/292)
> Use Ubuntu trusty

- Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/293)
> Add 'make fmt' task target

- package.json
- https://webpack.js.org/guides/tree-shaking/
- https://github.com/webpack/webpack/tree/0b13cf19a19fd64d176c77aecbbf00ec57966276/examples/side-effects
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/295)
> Add 'sideEffects' to allow webpack's advanced tree snaking

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/298)
> Add Node.js v10 to TravisCI matrix

- Makefile
This is regression by https://github.com/karen-irc/option-t/pull/299
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/300)
> Fix the regression: fail `make test` on some parallel case.

- Makefile
- ava_test/.eslintrc.js
- ava_test/test_example.js
- package.json
- yarn.lock
mocha is pretty stable test framework,
but it requires some transform to work with power-assert and
its nest is pretty unreadable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/310)
> Introduce avajs to write a unit test

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/316)
> Add "this library is inspired Option<T> and Result<T, E>" to README.

- Makefile
- package.json
- yarn.lock
Guides & Changelogs:
* https://babeljs.io/docs/en/v7-migration
* https://babeljs.io/blog/2018/08/27/7.0.0
* https://github.com/power-assert-js/babel-preset-power-assert/blob/master/CHANGELOG.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/320)
> Update babel to v7

- package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/321)
> Update all indirect dependencies by 'yarn upgrade'

- .eslintrc.js
- Makefile
- package.json
- tools/babel/babelconfig.js
- tools/babel/babelrc.cjs.js
- tools/babel/babelrc.esm.js
- tools/babel/babelrc.power_assert.js
- yarn.lock
I would not like to manage plugins anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/323)
> Move to use @babel/preset-env to tranform code from set plugins directly

- .travis.yml
See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/326)
> Remove 'sudo' from travis ci config

- .eslintignore
- .vscode/settings.json
- Makefile
- package.json
- src/.eslintrc.js
- src/Maybe/expect.ts
- src/Nullable/expect.ts
- src/Option.d.ts
- src/Option.js
- src/PlainOption/expect.ts
- src/PlainOption/map.ts
- src/PlainOption/unwrapOrElse.ts
- src/PlainResult/expect.ts
- src/PlainResult/index.ts
- src/PlainResult/unwrapOrElse.ts
- src/Result.js
- src/Undefinable/expect.ts
- yarn.lock
This is still hybrid approach with tslint.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/329)
> Use ESLint to lint typescript

- .travis.yml
https://github.com/yarnpkg/yarn/releases
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/331)
> Update yarnpkg in CI to v1.13

- Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/339)
> Run 'make test_distribution_contain_all' in 'make test' 

- Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/340)
> Remove unused clean up tasks from Makefile

- tools/pkg_files_tester.js
This api is stabilized in v11.14.
And we can use these in v10 as experimental.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/353)
> Use fs.promises directly

- tools/eslint/eslintrc_core.js
- tools/eslint/eslintrc_typescript.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/358)
> Update eslint configs to the latest of eslint-config-abema

- tsconfig.json
- tsconfig_cjs.json
- tsconfig_esm.json
- tsconfig_test.json
This disable tired warnings in eslint
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/359)
> Use diagnostics option only for codegen

- .travis.yml
https://github.com/yarnpkg/yarn/releases
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/360)
> Use the latest yarnpkg

- src/Option.d.ts
- src/Option.js
- src/Result.d.ts
- src/Result.js
* https://github.com/karen-irc/option-t/issues/232
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/361)
> Add 'deprecated' mark for deprecated announced constructors

- src/Maybe/index.ts
- src/Nullable/index.ts
- src/Undefinable/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/362)
> Stop to use 'export *' to stop unintended exports

- LICENSE.MIT
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/366)
> Update license mail address for Tetsuharu OHZEKI

- src/Maybe/and.ts
- src/Maybe/andThen.ts
- src/Maybe/map.ts
- src/Nullable/and.ts
- src/Nullable/andThen.ts
- src/Nullable/map.ts
- src/Undefinable/and.ts
- src/Undefinable/andThen.ts
- src/Undefinable/map.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/381)
> Allow to compile with TypeScript 3.5

- src/PlainOption/and.ts
- src/PlainOption/andThen.ts
- src/PlainOption/expect.ts
- src/PlainOption/index.ts
- src/PlainOption/map.ts
- src/PlainOption/mapOr.ts
- src/PlainOption/mapOrElse.ts
- src/PlainOption/or.ts
- src/PlainOption/orElse.ts
- src/PlainOption/tap.ts
- src/PlainOption/unwrap.ts
- src/PlainOption/unwrapOr.ts
- src/PlainOption/unwrapOrElse.ts
- src/PlainResult/Result.ts
- src/PlainResult/and.ts
- src/PlainResult/andThen.ts
- src/PlainResult/expect.ts
- src/PlainResult/index.ts
- src/PlainResult/map.ts
- src/PlainResult/mapErr.ts
- src/PlainResult/mapOrElse.ts
- src/PlainResult/or.ts
- src/PlainResult/orElse.ts
- src/PlainResult/tap.ts
- src/PlainResult/toOption.ts
- src/PlainResult/unwrap.ts
- src/PlainResult/unwrapOr.ts
- src/PlainResult/unwrapOrElse.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/385)
> Add comments for operators of PlainOption/PlainResult

- src/Option.d.ts
- src/PlainOption/drop.ts
- src/PlainOption/index.ts
- src/PlainResult/drop.ts
- src/PlainResult/index.ts
- src/Result.d.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/391)
> Add comments which explains undocumented design 

- ava_test/PlainOption/test_and.js
- ava_test/PlainOption/test_expect.js
- ava_test/PlainOption/test_or.js
- ava_test/PlainResult/expect/test_expect_err.js
- ava_test/PlainResult/expect/test_expect_ok.js
- ava_test/PlainResult/test_and.js
- ava_test/PlainResult/test_expect.js
- ava_test/PlainResult/test_or.js
- ava_test/PlainResult/test_to_option.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/394)
> Add tests for PlainOption/PlainResult

- package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/404)
> Update typescript-eslint to v1.11

- package.json
- src/.eslintrc.js
- test/utils.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/405)
> Upgrade ESLint to v6

- .circleci/config.yml
- .editorconfig
* This is MVP
* https://github.com/karen-irc/option-t/issues/355
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/356)
> Add CircleCI configuration

- .circleci/config.yml
Fix https://github.com/karen-irc/option-t/issues/435
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/440)
> Enable CI build for the latest Node.js

- .circleci/config.yml
Fix https://github.com/karen-irc/option-t/issues/436
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/441)
> Add the custom command to install npm packages

- bors.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/442)
> bors-ng should read CircleCI config

- .circleci/config.yml
- Makefile
This improves the readability of CI results
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/453)
> Extract 'make ci' to CircleCI's steps

- tools/eslint/eslintrc_core.js
- tools/eslint/eslintrc_typescript.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/458)
> Revendor eslintrc

- README.md
- src/Option.d.ts
- src/Option.js
- src/Result.d.ts
- src/Result.js
* This reverts commit 4d2e7011943709757edbb6bd01c802eddf937a1e, reversing
changes made to 52066b91257c33728472e85cf79633e56488009d. https://github.com/karen-irc/option-t/pull/460
* The commit log was wrong.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/461)
> Revert "Merge #460"

- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/472)
> yarn upgrade to update indirect dependencies

- CHANGELOG.md
- package.json
- yarn.lock
* https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html
* https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html
* https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-3.html
* https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html
* https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-5.html
* https://devblogs.microsoft.com/typescript/announcing-typescript-3-6/
* https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-rc/
* Fix https://github.com/karen-irc/option-t/issues/325
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/427)
> Update typescript compiler to v3.7

- package.json
- yarn.lock
https://github.com/karen-irc/option-t/issues/325
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/501)
> Update typescript to 3.7 stable

- __tests__/Maybe/xor.test.js
- src/Maybe/xor.ts
Fix https://github.com/karen-irc/option-t/issues/410
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/411)
> Implement xor() for Maybe

- package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/518)
> Update typescript compiler to 3.7.3 

- tools/eslint/eslintrc_core.js
- tools/eslint/eslintrc_typescript.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/519)
> Revendor eslint configs from eslint-config-abema

- tools/esmodule_path_rewrite_tester.js
This follow up  #520
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/521)
> Include lib/ for testing path rewriting

- tools/babel/babel-plugin-add-mjs-suffix.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/522)
> Clean up babel-plugin-add-mjs-suffix

- .editorconfig
- .eslintrc.js
- src/Option.js
- src/Result.js
with some minor cleanup related to editorconfig & eslint
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/525)
> Add configs for mjs

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/526)
> Update parts related to esm/ in README

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/528)
> Use node:13-buster as latest_nodejs_executor explicitly

- docs/idiom/Option.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/karen-irc/option-t/530)
> Use esm/ instead of lib/

- bors.toml
> Remove Reviewable specific config

- src/PlainResult/index.ts
This is follow up https://github.com/karen-irc/option-t/pull/608
> Export flatten() fron PlainResult/index

- .editorconfig
- tools/package_export_tester.js
- tools/package_json_rewriter/transformer/add_exports_field/main.js
- tools/package_json_rewriter/transformer/add_exports_field/public_api.js
- tools/public_api.mjs
https://github.com/karen-irc/option-t/issues/421
> Add exports fields to support dual export

- .github/workflows/ci.yml
see https://github.com/karen-irc/option-t/issues/443
> Add the config to run CI on GitHub Actions

- .github/dependabot.yml
try again https://github.com/karen-irc/option-t/pull/675
> Add GitHub Actions to dependabot control zone 

- .github/dependabot.yml
This follow up https://github.com/karen-irc/option-t/pull/676
> Use same labels for PRs by dependabot

- README.md
https://github.com/karen-irc/option-t/issues/443
> Fix the badge link for CI

- README.md
I wrote up some note which we discussed in https://github.com/karen-irc/option-t/issues/232
> Add some note why we deprecated a wrapper object

- .github/workflows/ci.yml
Fix https://github.com/karen-irc/option-t/issues/759
> Drop Node.js v12 from CI jobs and Add v15 job

- src/PlainOption/Option.ts
This is same follow up with PlainResult's one https://github.com/karen-irc/option-t/pull/753
> Add some memories about why we use same shape for PlainOption

- .github/dependabot.yml
- package.json
- yarn.lock
https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/
> Rebaseline TypeScript compiler to 4.1

- .eslintrc.cjs
- Makefile
- src/.eslintrc.cjs
- tsconfig_eslint.json
Follow up https://github.com/karen-irc/option-t/pull/798
> Apply ESLint for .cjs

- package.json
This library does not aim to provide a monad.
> Update keywords in package.json

- .github/workflows/publish_package_to_npm.yml
- Makefile
This is based on
https://docs.github.com/en/actions/guides/publishing-nodejs-packages
> Setup publishing package GitHub Actions workflow

- .github/workflows/publish_package_to_npm.yml
- Makefile
This follow up https://github.com/karen-irc/option-t/pull/852
> Cleanup npmrc before calling 'make publish'

- src/PlainOption/Option.ts
- src/PlainResult/Result.ts
See https://github.com/karen-irc/option-t/issues/861
> Use `interface` to define base container types.

- tsconfig.base.json
This is based on tsc v4.2's --init option
> Rebaseline tsconfig

- src/PlainOption/okOrElse.ts
- src/PlainResult/orElse.ts
This followup https://github.com/karen-irc/option-t/pull/967
> Clarify argument names again

- __tests__/ClassOption/type_definition.ts
- package.json
- yarn.lock
This take over https://github.com/karen-irc/option-t/pull/978
> Update prettier to v2.3

- .eslintrc.cjs
- tools/generate_import_path_list_markdown.mjs
- tools/package_json_rewriter/transformer/add_exports_field/ExportEntry.mjs
- tools/parse_argv.mjs
- tools/public_api/ExposedPath.mjs
- Depend on https://github.com/karen-irc/option-t/pull/1126
> Use class private instance property for tools scripts

- .github/workflows/ci.yml
See https://github.com/karen-irc/option-t/issues/1146
> Rename a branch name which CI subscribes to `main`

- src/PlainOption/drop.ts
- src/PlainResult/drop.ts
> Provide type alias for an argument function of `drop()`

- src/PlainOption/drop.ts
- src/PlainResult/drop.ts
This follow up https://github.com/karen-irc/option-t/pull/1153
> Expose Mut*** types

- src/PlainOption/Option.ts
- src/PlainResult/Result.ts
> [backport #1262] Improve the backward compatibility with v30 or former version

- .github/workflows/ci.yml
> Drop CI for Node.js 17

- docs/idiom/README.md
- docs/idiom/express_progress.md
- docs/idiom/from_promise_settled_result.md
- tools/pkg_files.json
> Add idiom about "Convert from PromiseSettledResult<T>) to PlainResult" 

- src/Maybe/toNullable.ts
- src/Maybe/toUndefinable.ts
- src/Nullable/toUndefinable.ts
- src/Undefinable/toNullable.ts
> Import type directly from the placed that defines them

- .github/workflows/ci_on_main.yaml
Reverts karen-irc/option-t#1388
It caused the regression of https://github.com/karen-irc/option-t/pull/1383
> Revert #1388

- .eslintrc.cjs
- package.json
- Fix https://github.com/karen-irc/option-t/issues/816
> Change package.json's `type` to `module`

- .github/workflows/_ci.yaml
> Drop Node.js 16 from our CI

- package.json
- yarn.lock
https://devblogs.microsoft.com/typescript/announcing-typescript-4-9-beta/
> Switch to TypeScript 4.9 beta

- tools/package_json_rewriter/transformer/add_exports_field/ExportEntry.mjs
Reverts karen-irc/option-t#1522
It reopened #1515
This revert it and try to fix #1515
> Revert "Fix the order of conditions in `exports` field in package.json"

- Makefile
- package.json
- tools/babel/babelrc.cjs.mjs
- tools/babel/babelrc.d.cts.mjs
- tools/fs_helper.mjs
- tools/transform_files_by_babel.mjs
- yarn.lock
`@babel/cli`'s options & behaviors are not intuitive...
And by this change, we can remove the dependency :)
> Replace @babel/cli with the codegen script

- src/PlainOption/Option.ts
- src/PlainResult/Result.ts
Improve code jump and the exception case to allow to touch properties of them.
> Improve inline documents for PlainResult/PlainOption

- src/Maybe/Maybe.ts
- src/Maybe/expect.ts
- src/Maybe/index.ts
- src/Maybe/unwrap.ts
- src/Nullable/Nullable.ts
- src/Nullable/expect.ts
- src/Nullable/index.ts
- src/Nullable/unwrap.ts
- src/Undefinable/Undefinable.ts
- src/Undefinable/expect.ts
- src/Undefinable/index.ts
- src/Undefinable/unwrap.ts
- tools/public_api/table.mjs
This do same things with https://github.com/karen-irc/option-t/pull/1550
> Move _unwrap_ and _expect_ to next to the `Nullable`/`Undefinable`/`Maybe` type definition

- tools/publish/.npmrc
This fix the regression since 72260275533f81b0ed4c1eee826c87f898f012c3 #1560
> Recover tools/publish/.npmrc

- Makefile
> Add `make generate_import_path_list_md` to the root

- CHANGELOG.md
- CHANGELOG_OLD.md
- README.md
- docs/wrapper_objects.md
- packages/option-t/package.json
- packages/option-t/src/ClassicOption/ClassicOption.d.ts
- packages/option-t/src/ClassicOption/ClassicOption.js
- packages/option-t/src/ClassicResult/ClassicResult.d.ts
- packages/option-t/src/ClassicResult/ClassicResult.js
- packages/option-t/src/Option.ts
- packages/option-t/src/PlainOption/Option.ts
- packages/option-t/src/PlainOption/index.ts
- packages/option-t/src/PlainResult/Result.ts
- packages/option-t/src/PlainResult/index.ts
- packages/option-t/src/Result.ts
> Move to https://github.com/option-t/option-t

- packages/option-t/.eslintrc.cjs
- packages/option-t/src/PlainOption/okOr.ts
- packages/option-t/src/PlainOption/toNullable.ts
- packages/option-t/src/PlainOption/toUndefinable.ts
- packages/option-t/src/PlainResult/or.ts
- packages/option-t/src/PlainResult/orElse.ts
- packages/option-t/src/PlainResult/toOption.ts
This enable https://typescript-eslint.io/rules/no-import-type-side-effects/
> Enable `@typescript-eslint/no-import-type-side-effects` to prevent an accidental side-effect import

- docs/README.md
- docs/migration/v34.md
- packages/option-t/tools/pkg_files.json
> Add migration guide to v34

- .github/workflows/ci_for_pr.yaml
> Remove bors-ng specific branch config

- packages/option-t/package.json
- packages/option-t/tools/package_json_rewriter/transformer/add_exports_field/ExportEntry.mjs
This retries #1639
This follow up #1522 #1525
This works fine with Node.js v12~v19.
> Set types field for "default" condition for each of dual exports

- packages/option-t/src/Maybe/andThen.ts
- packages/option-t/src/Maybe/andThenAsync.ts
- packages/option-t/src/Maybe/orElse.ts
- packages/option-t/src/Maybe/orElseAsync.ts
- packages/option-t/src/Nullable/andThen.ts
- packages/option-t/src/Nullable/andThenAsync.ts
- packages/option-t/src/Nullable/orElse.ts
- packages/option-t/src/Nullable/orElseAsync.ts
- packages/option-t/src/PlainOption/Option.ts
- packages/option-t/src/PlainOption/andThen.ts
- packages/option-t/src/PlainOption/andThenAsync.ts
- packages/option-t/src/PlainOption/drop.ts
- packages/option-t/src/PlainOption/orElse.ts
- packages/option-t/src/PlainOption/orElseAsync.ts
- packages/option-t/src/PlainResult/Result.ts
- packages/option-t/src/PlainResult/andThen.ts
- packages/option-t/src/PlainResult/andThenAsync.ts
- packages/option-t/src/PlainResult/drop.ts
- packages/option-t/src/PlainResult/orElse.ts
- packages/option-t/src/PlainResult/orElseAsync.ts
- packages/option-t/src/Undefinable/andThen.ts
- packages/option-t/src/Undefinable/andThenAsync.ts
- packages/option-t/src/Undefinable/orElse.ts
- packages/option-t/src/Undefinable/orElseAsync.ts
- packages/option-t/src/internal/Function.ts
- packages/option-t/src/internal/Mutable.ts
- Fix #1257
- Depends on #1660
> Add explicit variance annotation

- tsconfig.base.json
Fix https://github.com/option-t/option-t/issues/1671
> Enable tsc's `--verbatimModuleSyntax` option

- docs/migration/v38.md
Almost contents are duplicated. We don't have to keep them.
> Deduplicate docs/migration/v38.md

- .github/workflows/publish_package_to_npm.yaml
This do the same thing with #1818
> Use Node.js v18 within the container for publish the package

- .github/dependabot.yml
See:
- https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
- https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/
> Enable dependabot's groped update

- package-lock.json
- package.json
- packages/option-t/tsconfig.json
- tsconfig.base.json
- https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/
- https://devblogs.microsoft.com/typescript/announcing-typescript-5-3/
> Update TypeScript to v5.3

- packages/option-t/src/maybe/namespace.ts
- packages/option-t/src/plain_option/namespace.ts
- packages/option-t/src/plain_result/namespace.ts
- packages/option-t/src/undefinable/namespace.ts
- Fix https://github.com/option-t/option-t/issues/2025
- Fix https://github.com/option-t/option-t/issues/2026
- Fix https://github.com/option-t/option-t/issues/2027
- Fix https://github.com/option-t/option-t/issues/2029
> Add TODO for packages/option-t/src/*/namespace.ts

- packages/option-t/src/maybe/index.ts
- packages/option-t/src/nullable/index.ts
- packages/option-t/src/plain_result/index.ts
- packages/option-t/src/undefinable/index.ts
- Fix https://github.com/option-t/option-t/issues/2034
- Fix https://github.com/option-t/option-t/issues/2033
- Fix https://github.com/option-t/option-t/issues/2032
- Fix https://github.com/option-t/option-t/issues/2030
> Add TODO comments to `packages/option-t/src/*/index.ts`

- packages/option-t/src/plain_option/index.ts
- packages/option-t/src/plain_option/namespace.ts
- packages/option-t/src/plain_result/index.ts
- packages/option-t/src/plain_result/namespace.ts
- Fix https://github.com/option-t/option-t/issues/2064
- Fix https://github.com/option-t/option-t/issues/2038
- Fix https://github.com/option-t/option-t/issues/2100
- Fix https://github.com/option-t/option-t/issues/2118
> Don't expose `asMut()` operator from the each of root endpoint

- packages/option-t/src/plain_result/index.ts
- packages/option-t/src/plain_result/namespace.ts
- Fix https://github.com/option-t/option-t/issues/2119
- Fix https://github.com/option-t/option-t/issues/2120
- Fix https://github.com/option-t/option-t/issues/2109
- Fix https://github.com/option-t/option-t/issues/2065
- Fix https://github.com/option-t/option-t/issues/2066
- Fix https://github.com/option-t/option-t/issues/2068
> Add some comments for `./PlainResult/namespace` & `./PlainResult`

- packages/option-t/src/plain_option/index.ts
- packages/option-t/src/plain_option/namespace.ts
- Fix https://github.com/option-t/option-t/issues/2101
- Fix https://github.com/option-t/option-t/issues/2102
- Fix https://github.com/option-t/option-t/issues/2039
- Fix https://github.com/option-t/option-t/issues/2050
> Add some comments for `./PlainOption/namespace` & `./PlainOption`

- packages/option-t/src/plain_result/to_option.ts
This follow up 9b89175f279501c0806bad3efa0088516905ea28
> Fix the typo about the recommended function name

- packages/option-t/src/maybe/filter.ts
- packages/option-t/src/nullable/filter.ts
- packages/option-t/src/undefinable/filter.ts
This follows up https://github.com/option-t/option-t/issues/393
> Annotate filterWithEnsureType more correctly

- packages/option-t/src/maybe/maybe.ts
- packages/option-t/src/nullable/nullable.ts
- packages/option-t/src/undefinable/undefinable.ts
This is lesson by https://github.com/option-t/option-t/pull/2187
> Add why we need to keep simple union for `Nullable`, `Maybe`, and `Undefinable`.

- package.json
https://github.com/pnpm/pnpm/releases/tag/v9.0.0
Updated by `corepack use pnpm@9.0.4`
> Update pnpm to v9

- packages/api_tests/__tests__/exposed_path/helper.mjs
- packages/option-t/tools/test_package_json_exports_field_format.mjs
This follows up:
- https://github.com/option-t/option-t/pull/2014
- https://github.com/option-t/option-t/pull/2017
> Cleanup unused test codes

- package.json
https://github.com/pnpm/pnpm/releases/tag/v9.1.1
> Update pnpm to v9.1.1

- packages/api_tests/__tests__/plain_result/try_catch/try_catch_and_map_err_fallback.test.mjs
- packages/api_tests/__tests__/plain_result/try_catch/try_catch_with_ensure_error.test.mjs
- packages/api_tests/__tests__/plain_result/try_catch_async/try_catch_and_map_err_fallback_async/producer_is_async_fn.test.mjs
- packages/api_tests/__tests__/plain_result/try_catch_async/try_catch_and_map_err_fallback_async/producer_is_normal_fn.test.mjs
- packages/api_tests/__tests__/plain_result/try_catch_async/try_catch_with_ensure_error_async/producer_is_async_fn.test.mjs
- packages/api_tests/__tests__/plain_result/try_catch_async/try_catch_with_ensure_error_async/producer_is_normal_fn.test.mjs
- packages/api_tests/__tests__/plain_result/unwrap_or_throw/throw_error_with_assert.test.mjs
- packages/option-t/src/internal/error_message.ts
- packages/option-t/src/plain_result/try_catch.ts
- packages/option-t/src/plain_result/try_catch_async.ts
- packages/option-t/src/plain_result/unwrap_or_throw_error.ts
This follows up
- https://github.com/option-t/option-t/pull/2287
- https://github.com/option-t/option-t/pull/2289
> Deduplicate "an instance of Error of the current realm." string

- docs/migration/README.md
Fix https://github.com/option-t/option-t/issues/2291
> Add the link for v49 release note to docs/migration/README.md

- docs/migration/README.md
- docs/migration/v47.md
- docs/migration/v49.md
Fix https://github.com/option-t/option-t/issues/2292
> Add migration guide v49

- docs/public_api_list.md
- packages/option-t/tools/generate_import_path_list_markdown.mjs
- packages/option-t/tools/generate_import_path_list_markdown/md_list_item.js
- packages/option-t/tools/generate_import_path_list_markdown/md_type_section.js
- packages/option-t/tools/public_api/api_path_descriptor.mjs
- packages/option-t/tools/public_api/exposed_path.mjs
- packages/option-t/tools/public_api/table.mjs
Fix https://github.com/option-t/option-t/issues/2290
> Refine docs/public_api_list.md

- packages/option-t/src/plain_result/try_catch.ts
- packages/option-t/src/plain_result/try_catch_async.ts
- Fix https://github.com/option-t/option-t/issues/2296
- Fix https://github.com/option-t/option-t/issues/2295
> Add JSDoc to new `tryCatchIntoResultWithEnsureError` impls

- package.json
This is done by `corepack up`.
> Update pnpm to 9.1.4

- package.json
> Update pnpm to 9.4.0

- package.json
> Update pnpm to v9.10

- docs/idiom/README.md
- docs/idiom/infer.md
Added idiom for the `Infer` type discussed in https://github.com/option-t/option-t/issues/2362.
close https://github.com/option-t/option-t/issues/2362
> docs: add idiom of infer utility types

- packages/option-t/package.json
- packages/option-t/tools/package_json_rewriter/transformer/add_exports_field/export_entry.mjs
- packages/option-t/tools/test_package_json_exports_field_format.mjs
Fix https://github.com/option-t/option-t/issues/2380
> add support for module-sync

- package.json
> Update pnpm to v9.12.2 by `corepack up`

- package.json
- pnpm-lock.yaml
According to their blog, I think this does not require our next release will be a breaking change
https://devblogs.microsoft.com/typescript/announcing-typescript-5-7/
> Update typescript to v5.7

- package.json
> Update pnpm to 10.1 by corepack up

- eslint.config.js
Fix https://github.com/option-t/option-t/issues/2441
> Enable ESLint's `reportUnusedInlineConfigs` option

- packages/api_tests/package.json
- packages/api_typing_tests/package.json
- packages/option-t/package.json
- packages/test_module_resolution_bundler/package.json
- packages/test_module_resolution_node16/package.json
- packages/test_module_resolution_node_next/package.json
- pnpm-lock.yaml
See https://pnpm.io/workspaces
> Use pnpm's `workspace:` protocol 

- .github/workflows/_ci.yaml
Fix https://github.com/option-t/option-t/issues/2384
> Drop Node.js v20 from CI

- Makefile
- package.json
This is for npm but pnpm does not use it.
> Remove `workspaces` setting from package.json

- packages/test_module_resolution_node16/tsconfig.json
- packages/test_module_resolution_node_next/tsconfig.json
https://www.typescriptlang.org/docs/handbook/modules/reference.html#the-module-compiler-option
> Specify `--module` options explicitly for import-types test

- packages/test_module_resolution_node16/tsconfig.json
- packages/test_module_resolution_node_next/tsconfig.json
This try https://github.com/option-t/option-t/pull/2469 again
> Retry #2469: Specify --module options explicitly for import-types test

- packages/option-t/package.json
- packages/option-t/tools/package_json_rewriter/transformer/add_exports_field/export_entry.mjs
- packages/option-t/tools/test_package_json_exports_field_format.mjs
- packages/test_module_resolution_node16/src/classic_option.cts
- packages/test_module_resolution_node16/src/classic_result.cts
- packages/test_module_resolution_node16/src/index.cts
- packages/test_module_resolution_node16/src/maybe.cts
- packages/test_module_resolution_node16/src/nullable.cts
- packages/test_module_resolution_node16/src/plain_option.cts
- packages/test_module_resolution_node16/src/plain_result.cts
- packages/test_module_resolution_node16/src/undefinable.cts
- packages/test_module_resolution_node_next/src/classic_option.cts
- packages/test_module_resolution_node_next/src/classic_result.cts
- packages/test_module_resolution_node_next/src/index.cts
- packages/test_module_resolution_node_next/src/maybe.cts
- packages/test_module_resolution_node_next/src/nullable.cts
- packages/test_module_resolution_node_next/src/plain_option.cts
- packages/test_module_resolution_node_next/src/plain_result.cts
- packages/test_module_resolution_node_next/src/undefinable.cts
Fix https://github.com/option-t/option-t/issues/2472
> Drop `"require"` condition from exports in package.json

- packages/option-t/tools/package_json_rewriter/transformer/add_exports_field/export_entry.mjs
- packages/option-t/tools/test_package_json_exports_field_format.mjs
This follows up https://github.com/option-t/option-t/pull/2480
> Clean up CommonJS relatec code vestiges

- .github/actions/prepare_ci/action.yaml
- .github/workflows/_ci.yaml
- .github/workflows/publish_package_to_npm.yaml
This would be updated by dependabot.
> Hardening reusable github actions' versions

- README.md
- docs/README.md
- docs/how_to_import.md
- docs/installation.md
Fix https://github.com/option-t/option-t/issues/2473
> Update README.md to follow to drop CommonJS support

- packages/option-t/package.json
- packages/option-t/tools/package_json_rewriter/transformer/add_exports_field/export_entry.mjs
- packages/option-t/tools/test_package_json_exports_field_format.mjs
These conditions will be covered by `default` condition.
> Drop some export conditions

- packages/option-t/src/deprecated/plain_option/internal/intermediate_namespace.ts
- packages/option-t/src/maybe/internal/intermediate_namespace.ts
- packages/option-t/src/nullable/internal/intermediate_namespace.ts
- packages/option-t/src/plain_result/internal/intermediate_namespace.ts
- packages/option-t/src/undefinable/internal/intermediate_namespace.ts
> Remove obsoleted comments about #2173

- package.json
> Update pnpm to 10.15.1 by 'corepack up'

- .github/actions/prepare_ci/action.yaml
- https://github.com/actions/setup-node/releases/tag/v5.0.0
- Close https://github.com/option-t/option-t/pull/2657
> Update actions/setup-node from 4.4.0 to 5.0.0
